### ISSUE TITLE
Memory leak issue with Greenmail

### ISSUE THREAD

**Issue by cgaulay** [greenmail-mail-test/greenmail#100]
Hi,

j've installed Greenmail as a webapp but there is a problem in catalina logs : 

oct. 06, 2015 5:14:48 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads Avertissement: The web application [/greenmail] appears to have started a thread named [Thread-1031] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread: com.icegreen.greenmail.imap.ImapRequestLineReader.nextChar(ImapRequestLineReader.java:66) com.icegreen.greenmail.imap.ImapRequestLineReader.consumeLine(ImapRequestLineReader.java:166) com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:55) com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:94) com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:103) java.lang.Thread.run(Thread.java:744)

Do you know this issue ? 

Thanks in advance,
Regards

**Comment by marcelmay** [comment]
Hi @cgaulay,

which version did you use of GreenMail and of Tomcat?

Thx,
Marcel

**Comment by cgaulay** [comment]
Hi @marcelmay ,

i use GreenMail 1.4.1 on a Tomcat7 server.

Charly

**Comment by cgaulay** [comment]
Hi @marcelmay,

just a little precision : I use Javax Mail  API to connect and browse mailbox in GreenMail webapp.
And during some tests, I've noted this :
when I try to connect on a store with imap using store.connect(mailhost, mailport, mailuser, mailpassword) with wrong login/password (user don't exists on GreenMail), I've got a Javax Mail exception (that's normal) :
javax.mail.AuthenticationFailedException: LOGIN failed. Invalid login/password

But in jvisualvm, cpu usage takes between 12 or 15% for each connection attempt ! and the cpu usage don't decrease after.
I can't explain why Java Mail exception generate a cpu charge but in my case, the solution is to use POP3

With pop3, store.connect with wrong login/password generate an exception but cpu isn't impacted.

Regards,

**Comment by marcelmay** [comment]
It seems that tomcat incorrectly complained, as the thread stack shows GreenMail processing an IMAP request. Looks like a client still has an open connection with GreenMail. Therefore, I'll flag the issue as invalid.
