### ISSUE TITLE
Greenmail webapp war does not deploy in Tomcat 7.0.63

### ISSUE THREAD

**Issue by hotmeatballsoup** [greenmail-mail-test/greenmail#105]
I downloaded the [Greenmail WAR]() from your Downloads link, which prompted my machine to download `greenmail-webapp-1.4.1.war`.

I then moved this WAR to my `$TOMCAT_HOME/webapps` directory and ran Tomcat (7.0.63) like normal (`$TOMCAT_HOME/bin/startup.sh`).

I tailed the `$TOMCAT_HOME/logs/catalina.out` log for errors and don't see any. According to the logs, Greenmail deployed just fine.

I then go to `http://localhost:8080/greenmail-webapp-1.4.1` and am getting a 404 (not found) error from Tomcat. I am trying to access a UI where I can see a history of all the mail that my JVM apps have "sent" to Greenmail.

Please advise!

**Comment by marcelmay** [comment]
As described in the [documentation](http://www.icegreen.com/greenmail/#deploy_webapp), GreenMail webapp is only a deployment wrapper, configuring GreenMail via web.xml settings.

If you want to see mails, please use a standard mail client (Thunderbird, Mail.app, ...) and connect to either GreenMail IMAP server (activate in web.xml) or POP3 server (localhost:10110). 

If you can send mails to GreenMail, then GreenMail WAR is running. You can also check the Tomcat Web Application Manager (http://localhost:8080/manager/html).

As an improvement, I'll add an enhancement for at least providing a default page showing GreenMail configuration.

**Comment by hotmeatballsoup** [comment]
Thanks @marcelmay!

Yes, directions for how to activate the GreenMail IMAP server in `web.xml` and then connect to it from a client (say, Thunderbird) would be *enormously* appreciated!

**Comment by buildscientist** [comment]
Closing as an enhancement has been opened in #106
