### ISSUE TITLE
Problem testing multi-part emails

### ISSUE THREAD

**Issue by rbaldock** [greenmail-mail-test/greenmail#107]
When I try to test the sending of a multi-part MIME message using:

GreenMailUtil.sendMimeMessage(multiPartMimeMessage);

No message is received.

However, when I use:
	    
user.deliver(multiPartMimeMessage);

The message is received.

What's the difference between these two methods?

Robert

**Comment by buildscientist** [comment]
Hi @rbaldock - when you invoke:
``` java
GreenMailUtil.sendMimeMessage(multiPartMimeMessage); 
```
As stated in the Javadocs for the method there is an assumption that an instance of Session is already defined in your MimeMessage. 

See the JavaDocs for [MimeMessage](https://docs.oracle.com/javaee/7/api/javax/mail/internet/MimeMessage.html) for more details - the default constructor expects an instance of [Session](https://docs.oracle.com/javaee/7/api/javax/mail/Session.html)

A call to:
``` java
 user.deliver(multiPartMimeMessage); 
```
Actually takes the MimeMessage and stores it directly in the GreenMail IMAP/POP3 MailFolder (e.g. in memory) 

Does that make sense?

**Comment by rbaldock** [comment]
Thanks for that.  I am constructing my MimeMessage around a Session which I create like this:

	Properties props = System.getProperties();
        props.put("mail.smtp.host", LOCALHOST);
        props.put("mail.smtp.port", "10025");
        
        Session session = Session.getInstance(props, null);

It works OK for regular MimeMessages but doesn't seem to for multi-part messages.

If you know of a code snippet for testing multi-part messages, that would be much appreciated.


Robert

**Comment by buildscientist** [comment]
@rbaldock A quick Google search brought up the following [blog entry](http://www.aviyehuda.com/blog/2009/12/07/send-a-multipart-smtp-email-message-with-java/) that has examples of sending a multi-part MimeMessage. 

If you're not comfortable using JavaMail - I'd recommend looking at the following libraries: 

* [Apache Commons Email](http://commons.apache.org/proper/commons-email/)
* [Spring](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mail.html)

I'm going to close this issue as there is no issue sending multi-part emails into GreenMail.

**Comment by rbaldock** [comment]
As this issue has been closed, I'm not sure I can reply to it.

I know how to create a multi-part MimeMessage in Java.  What I was 
looking for was an example of a Greenmail test which uses multi-part 
messages as I wasn't able to get it working.  It doesn't even seem to 
throw an error.

However, I shall keep investigating to see whether there's an issue with 
the way I'm constructing my message.


Robert

**Comment by marcelmay** [comment]
You can have a look at some of tests, eg [ImapServerTest.testRetriveMultipart](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/test/ImapServerTest.java),  ~line 95,
or directly in [GreenMailUtil. sendMimeMessage](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMailUtil.java) ~line 260.
