### ISSUE TITLE
JavaMail can't parse BODYSTRUCTURE for inline attachment

### ISSUE THREAD

**Issue by DavidWhitlock** [greenmail-mail-test/greenmail#113]
First off, I really like what you've done with GreenMail and I'm super happy about being able to test my JavaMail code with an embedded IMAP server.

While writing some integration tests with GreenMail, I came across what I believe is a defect in GreenMail's IMAP server.  When I send a mail message with an inline text/plain attachment to GreenMail via SMTP, JavaMail can't parse the BODYSTRUCTURE portion of the message when it is fetched using IMAP.

I whittled down my integration test to this unit tests which appears to reproduce the issue:

https://github.com/DavidWhitlock/greenmail/blob/b4afb82a77db215170d73589132b40c57ef6c0e2/greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleSendReceiveMessageWithInlineAttachmentTest.java

When the test invokes `getContentType` on the message fetched from the GreenMail IMAP server, this exception is thrown:

```
javax.mail.MessagingException: Unable to load BODYSTRUCTURE

	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1488)
	at com.sun.mail.imap.IMAPMessage.getContentType(IMAPMessage.java:556)
	at com.icegreen.greenmail.examples.ExampleSendReceiveMessageWithInlineAttachment.fetchEmailWithInlineAttachment(ExampleSendReceiveMessageWithInlineAttachment.java:66)
	at com.icegreen.greenmail.examples.ExampleSendReceiveMessageWithInlineAttachment.sendAndFetchMailMessageWithInlineAttachment(ExampleSendReceiveMessageWithInlineAttachment.java:55)
```

Enabling JavaMail IMAP debugging reveals that it cannot parse the parameter name to the inline disposition:

```
DEBUG IMAP: parsing BODYSTRUCTURE
DEBUG IMAP: msgno 1
DEBUG IMAP: parsing multipart
DEBUG IMAP: parsing BODYSTRUCTURE
DEBUG IMAP: msgno 1
DEBUG IMAP: single part
DEBUG IMAP: type TEXT
DEBUG IMAP: subtype PLAIN
DEBUG IMAP: parameter name charset
DEBUG IMAP: parameter value us-ascii
DEBUG IMAP: cParams ; charset=us-ascii
DEBUG IMAP: id null
DEBUG IMAP: description null
DEBUG IMAP: encoding 7bit
DEBUG IMAP: size 40
DEBUG IMAP: lines 0
DEBUG IMAP: disposition inline
DEBUG IMAP: parameter name null
```

I spent a little time debugging this, but seeing as I'm not familiar with mail RFCs, I'm not sure what the correct format of the BODYSTRUCTURE should be.  (Maybe GreenMail shouldn't be sending over an empty parameter list.  I'll try a similar test with GMail's IMAP server and see what it returns.)

Anyway, thanks again for GreenMail and, if I make more progress on understanding this defect, I'll let you know what I find.

Thanks,

Dave

**Comment by marcelmay** [comment]
Hi @DavidWhitlock ,

thanks for providing a test. I'll look into it.

**Comment by DavidWhitlock** [comment]
I sent an email to my GMail account that had an inline text/plain attachment (note that the text in this attachment is larger than the one in the test).  When I ran the test using GMail's IMAP server, JavaMail was able to parse the message.  I think this is the relevant debugging output:

```
DEBUG IMAP: parsing BODYSTRUCTURE
DEBUG IMAP: msgno 12
DEBUG IMAP: single part
DEBUG IMAP: type TEXT
DEBUG IMAP: subtype PLAIN
DEBUG IMAP: parameter name CHARSET
DEBUG IMAP: parameter value us-ascii
DEBUG IMAP: cParams ; charset=us-ascii
DEBUG IMAP: id null
DEBUG IMAP: description null
DEBUG IMAP: encoding 7BIT
DEBUG IMAP: size 326
DEBUG IMAP: lines 10
DEBUG IMAP: disposition INLINE
DEBUG IMAP: parameter list NIL
DEBUG IMAP: dParams null
DEBUG IMAP: all DONE
```

The `parameter list NIL` might be relevant.  In the failing test, GreenMail send back this response to JavaMail:

```
* 1 FETCH (BODYSTRUCTURE (("TEXT" "PLAIN" ("charset" "us-ascii") NIL NIL "7bit" 40 0 NIL ("inline" ()) NIL) "mixed" ("boundary" "----=_Part_0_1010670443.1452452069288") NIL NIL))
```

Perhaps the `("inline" ())` should be  `("inline" NIL)`?

Yeah.  I ran the debugger with the GMail IMAP and this is the response that it sent:

```
* 12 FETCH (BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "us-ascii") NIL NIL "7BIT" 326 10 NIL ("INLINE" NIL) NIL)("APPLICATION" "ZIP" ("NAME" "David_Whitlock.zip") NIL "David Whitlock's Project1" "BASE64" 6124 NIL ("ATTACHMENT" ("FILENAME" "David_Whitlock.zip")) NIL) "MIXED" ("BOUNDARY" "----=_Part_0_12209492.1452451358564") NIL NIL))
```

Looks like `("INLINE" NIL) is the way to go.

**Comment by marcelmay** [comment]
Hi David,

you're right - that was the issue.

I fixed it and uploaded a new [Maven snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/greenmail/1.4.2-SNAPSHOT) (or pull and build GreenMail yourself).

Cheers,
Marcel

**Comment by DavidWhitlock** [comment]
Excellent, @marcelmay.  I used the snapshot version and my test passed.  Please consider this issue closed.
