### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by buildscientist** [greenmail-mail-test/greenmail#123]
Just realized we don't have a contributor code of conduct in our project. I don't think this is an issue between us as maintainers but I think we should make it clear to our users/contributors that we have a code of conduct. 

See the [code covenant](http://contributor-covenant.org/version/1/4/code_of_conduct.md) for more details.

/cc @marcelmay @camann9

**Comment by buildscientist** [comment]
Bump @marcelmay - do you think we need this? I think it would be nice to at least add a link to our README.md. We don't currently have any problems but it might prevent something in the future.

**Comment by marcelmay** [comment]
Had not problems in the last 10 years with GreenMail.
