### ISSUE TITLE
Make release artifacts available on release tab

### ISSUE THREAD

**Issue by buildscientist** [greenmail-mail-test/greenmail#125]
A number of other projects make release artifacts available on the release page. 

I think we should at least make greenmail-standalone and the WAR downloadable to save our users time from having to build these artifacts on their own. 

We can grab the artifacts off of CircleCI or off of Maven central. 

/cc @marcelmay @camann9

**Comment by marcelmay** [comment]
Artifacts are available via site (http://www.icegreen.com/greenmail/#download), which is primary location for users and links to release notes. Releases do contain link to Maven Central, where also WARs can be downloads. Added additional link to GreenMail site download section.
