### ISSUE TITLE
Delete mailbox account

### ISSUE THREAD

**Issue by cgaulay** [greenmail-mail-test/greenmail#128]
Hi all, 

is there any way to delete a mailbox account or mailbox user created by GreenMail ?
i explain you :
GreenMail is deployed like a webapp application.
I use it like a smtp server which catches and create all of mail if it doesn't exists.
But, i want to delete mailbox without shutdown greemail server.
Is it possible ?

thanks in advance,
Regards

**Comment by buildscientist** [comment]
Unfortunately if GreenMail is deployed as a web service/application there's no way of deleting (or adding) users/mailboxes while the service is running. 

You would need to pre-define the users in the [web.xml](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-webapp/src/main/webapp/WEB-INF/web.xml) file as follows: 

```xml
<context-param>
    <param-name>greenmail.users</param-name>
    <param-value>
      user1:password@localhost
      user2:password2@localhost
    </param-value>
  </context-param>
```

We are planning on introducing a RESTful API (see #108 for more details) that will allow you add/delete users while the service is running.
