### ISSUE TITLE
Race condition when receiving emails other SMTP

### ISSUE THREAD

**Issue by pbugalski-atlassian** [greenmail-mail-test/greenmail#132]
There exists a race condition which leads to a client reporting message send error while greenmail SMTP server informed test that all mail has been correctly received.

Imagine following test scenario:
1. greenmail SMTP server is started
2. test code is waiting until an email is received
3. once the email is received greenmail SMTP server is closed

In this scenario the client that was sending the email should receive from greenmail SMTP server confirmation that the email was correctly send. Unfortunately because of race condition it is possible for the client to read  EOF from its connection to greenmail SMTP server rather than an expected confirmation response.

This is possible under following conditions:
1. greenmail SMTP server is started
2. test code is waiting until an email is received (thread A)
3. client sends email and it is correctly received by greenmail SMTP server (thread B)
4. greenmail SMTP server informs all listeners that email was received before it sends response to the client (thread B)
5. test code stops greenmail server which in turn closes all open sockets (thread A)
6. socket to the client is closed before thread B was able to send response to the client

In greenmail there is a test case that checks a similar scenario: com.icegreen.greenmail.test.SmtpServerTest#testSmtpServerReceiveInThread
But crucially it is waiting for a thread running SMTP client to correctly end its execution before calling stop on greenmail SMTP server. As a result this race condition can not occur.

**Comment by marcelmay** [comment]
Thx alot, @pbugalski-atlassian  .

The test is quite long running, with some tweaks I got it down to half the time but still too long for a unit test. Maybe I'll put it in a separate test suite of long running tests ...

**Comment by pbugalski-atlassian** [comment]
This test was meant to be more of a way to show case the issue rather then a proper unit test. Initially I thought it could be simply removed once this PR is accepted but I like the idea of separate suite for more complex and time consuming tests.

**Comment by marcelmay** [comment]
Closing, request pulled and long running test moved to integration tests (#141)
