### ISSUE TITLE
circleci will show build with failed tests as successful

### ISSUE THREAD

**Issue by pbugalski-atlassian** [greenmail-mail-test/greenmail#134]
Here is a build with a failed test and status success: https://circleci.com/gh/greenmail-mail-test/greenmail/156#tests

**Comment by buildscientist** [comment]
We have a [shell script](https://github.com/greenmail-mail-test/greenmail/blob/master/.circleci/parallelize_build.sh) that runs on CircleCI to parallelize the builds. 

It's likely I need to capture an error return code from Maven when mvn test runs and fail the build accordingly. 

Thanks for the heads up.

**Comment by buildscientist** [comment]
@pbugalski-atlassian I'm curious - do you work for Atlassian? Are you using GreenMail internally for testing purposes?

**Comment by pbugalski-atlassian** [comment]
Yes. We do use GreenMail for some of our test automation at Atlassian. For example some of our functional test in JIRA use it.
