### ISSUE TITLE
Greenmail-standalone JAR missing from Maven Central

### ISSUE THREAD

**Issue by buildscientist** [greenmail-mail-test/greenmail#136]
@marcelmay Looks like the link on our website for greenmail-standalone returns a 404. When I try to view the directory I don't see a greenmail-standalone.jar

Was the jar pushed when you issued a mvn deploy?

**Comment by buildscientist** [comment]
Looks like the artifact is on Maven central but the link on our site is incorrect

It's http://central.maven.org/maven2/com/icegreen/greenmail/1.5.0/greenmail-standalone-1.5.0.jar when it should be http://central.maven.org/maven2/com/icegreen/greenmail-standalone/1.5.0/greenmail-standalone-1.5.0.jar

**Comment by marcelmay** [comment]
Published site
