### ISSUE TITLE
How do I store incoming mail to database?

### ISSUE THREAD

**Issue by mrniko** [greenmail-mail-test/greenmail#137]

**Comment by buildscientist** [comment]
There's a number of ways you can do this. Keep in mind that data does not persist after restarts of GreenMail. 

You can: 

- Download the email using Javamail and store the raw email into a database
- Store a serialized [MimeMessage](https://javamail.java.net/nonav/docs/api/javax/mail/internet/MimeMessage.html)  in your database

The question is rather arbitrary and unrelated to GreenMail overall so I'm going to go ahead and close this.

**Comment by mrniko** [comment]
@buildscientist thank you
