### ISSUE TITLE
message/rfc822

### ISSUE THREAD

**Issue by anton-johansson** [greenmail-mail-test/greenmail#142]
I'm having some troubles with a part in an e-mail that is of type message/rfc822. I'm getting an NPE. I assume it is because this section isn't implemented:
https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java#L249

Any plans on implementing it?

**Comment by marcelmay** [comment]
@anton-johansson, do you have a test case?

**Comment by anton-johansson** [comment]
I will try and provide a test case later today, if I find the time. :)

**Comment by buildscientist** [comment]
Hi @anton-johansson do you have any updates on providing a test case? Thanks.

**Comment by marcelmay** [comment]
I got a test case now, an look into this.

**Comment by marcelmay** [comment]
@anton-johansson : I just updated [Maven snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/greenmail/1.5.2-SNAPSHOT), maybe you can give it a try. The test case [Rfc822MessageTest](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/test/specificmessages/Rfc822MessageTest.java) works, please reopen if you still see the issue.
