### ISSUE TITLE
Support UIDPLUS extension : UID EXPUNGE, APPENDUID, COPYUID

### ISSUE THREAD

**Issue by SkittishSloth** [greenmail-mail-test/greenmail#145]
I've been using greenmail for testing, and it's performed wonderfully in every use case I've thrown at it until the other day. We're using UID EXPUNGE against our IMAP server, and in creating unit tests for that it seems that greenmail doesn't support it.

Is there some way to mock this out, at least so I don't get a BadCommandException? Would it be difficult to implement on the greenmail side of things? (I'm sure I can work around it on my end with some refactoring and better mocking, but I like having an embedded IMAP server to make sure things are actually working correctly.)

**Comment by marcelmay** [comment]
Hi @SkittishSloth , can you provide a simple test case?

**Comment by SkittishSloth** [comment]
Sure - and btw, it looks like it's part of the UIDPLUS RFC (4315, https://tools.ietf.org/html/rfc4315). I don't recall if I've tried anything else in that RFC, and I have no clue if you would want to do anything with the rest of it anyways, but it's worth a look at least.

This is an extremely simple/contrived case, but it's pretty close to what I'm trying to do. IMAPFolder instances are (in my experience) only obtainable by a cast from a Folder returned from an IMAPStore instance (which in turn are only obtainable via casting, but you shouldn't necessarily need to cast the Store instance just to get the folder).

```java
    public void uidExpunge(final IMAPFolder folder) throws MessagingException {
      try {
        final long messageId = 1234L; // or whatever UID you can use for testing.
        folder.open(Folder.READ_WRITE);
        final Message message = folder.getMessageByUID(messageId);
        message.setFlag(Flags.Flag.DELETED, true);
        final Message[] toDelete = new Message[]{message};
        folder.expunge(toDelete);
      } finally {
        folder.close(false);
      }
    }
```

Is that sufficient? Let me know if you need any thing more. Thanks!

**Comment by marcelmay** [comment]
Thx alot, already got UID EXPUNGE working but have not pushed it yet.

Before pushing I'll have to check the rest of the UIDPLUS spec, as I had to add UIDPLUS to the capabilities. UIDPLUS not only extends EXPUNGE but also extends COPY and APPEND response codes.

**Comment by marcelmay** [comment]
Final missing part, coming soon : COPYUID

**Comment by marcelmay** [comment]
#114 already implemented COPYUID, so GreenMail now fully supports UIDPLUS.

@SkittishSloth , we plan a 1.5.1 release by the end of the month and just deployed latest version as [1.5.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/). If you notice any bugs in the SNAPSHOT, please reopen this issue.

**Comment by SkittishSloth** [comment]
That's great - thanks!
