### ISSUE TITLE
GreenMailUtil#getHeaders produces StringIndexOutOfBoundsException for empty MIME parts

### ISSUE THREAD

**Issue by jheilgeist** [greenmail-mail-test/greenmail#151]
One of my test messages has an empty MIME part:

```
--Apple-Mail-02CA0876-60CA-4142-8D95-96CC72E28AC5
Content-Type: text/plain;
	charset=us-ascii
Content-Transfer-Encoding: 7bit



--Apple-Mail-02CA0876-60CA-4142-8D95-96CC72E28AC5--
```

When retrieving the headers of this MIME part, GreenMail fails with a `StringIndexOutOfBoundsException` in `GreenMailUtil#getHeaders(Part)`. The reason is, that `GreenMailUtil#getWholeMessage(Part)` returns the **trimmed** part content and `GreenMailUtil#getHeaders(Part)` doesn't consider the fact, that `all.indexOf("\r\n\r\n")` may return a `-1`. The same error is also in `GreenMailUtil#getBody(Part)`.

**Comment by camann9** [comment]
Could you send us a pull request with the fix and a unit test?

**Comment by buildscientist** [comment]
Or even just the unit test would be fine. Either submit the test as part of a PR or inline in this issue. Thanks.

**Comment by marcelmay** [comment]
@jheilgeist : Please reopen if still not fixed. Test is [GreenMailUtilTest.testGetEmptyBodyAndHeader()](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/test/GreenMailUtilTest.java#LC46)
