### ISSUE TITLE
getReceivedMessages ordering

### ISSUE THREAD

**Issue by gionn** [greenmail-mail-test/greenmail#162]
Hi,

when calling getReceivedMessages, we obtain an array that looks like is unordered, while an ordering based on the received date would be great.

Can someone confirm the actually such API doesn't return email messagge in any particular order?

Thanks.

**Comment by camann9** [comment]
In the code (HierarchicalFolder.appendMessage) it looks like messages within one mailbox should be stored by GreenMail in the order in which they were received (and returned in that order looking at other places in the code). But this is not guaranteed and you should explicitly sort them if you needsorted data.
