### ISSUE TITLE
waitForIncomingEmail and CC/BCC

### ISSUE THREAD

**Issue by keirlawson** [greenmail-mail-test/greenmail#168]
I'm trying to write a test to check that 100 emails will be sent, however the software under test test to send the emails using the BCC field, so it might send 10 mails with 10 addresses BCCed each.  The exact manner in which the emails are batched I don't care about and so don't want to write into my test, I just want to check that I get all 100 emails sent at the end of the day. Calling `getReceivedMessages()` reports that there are indeed the expected 100 messages if I wait long enough, however, `waitForEmailsRecieved()` seems to not be usable for this wait as it considers an email with 10 BCCs as a single email, and I don't know exactly how the emails will be batched in advance.  Is there some way of waiting for a set number of received messages as per the `getReceivedMessages()` call rather than using `waitForEmailsRecieved()`?

**Comment by marcelmay** [comment]
@keirlawson , I'll look into this.

**Comment by marcelmay** [comment]
@keirlawson : Which greenmail version do you use, was your timeout sufficient when waiting?

I tried to create a test case sending one mail with two BCCs which runs ok:
```
@Test
public void testSendAndWaitForIncomingMailsInBcc() throws Throwable {
        // Create a test email with 2 BCC
        String subject = GreenMailUtil.random();
        String body = GreenMailUtil.random();
        final MimeMessage message = createTextEmail("test@localhost", "from@localhost", subject, body, greenMail.getSmtp().getServerSetup());
        message.addRecipients(Message.RecipientType.BCC, "bcc1@localhost,bcc2@localhost");

        assertEquals(0, greenMail.getReceivedMessages().length);

        GreenMailUtil.sendMimeMessage(message);

        // Expect 1 + 2 BCCs mails
        assertTrue(greenMail.waitForIncomingEmail(1500, 3));

        MimeMessage[] emails = greenMail.getReceivedMessages();
        assertEquals(3, emails.length);
}
```

**Comment by marcelmay** [comment]
@keirlawson,  would the test above reproduce your issue?
Do you still experience this issue with latest version 1.5.2?

**Comment by buildscientist** [comment]
@keirlawson Any updates on this? I wasn't able to find waitForEmailsRecieved() in the existing codebase - can you tell us what version of GreenMail you're using? 

The example that @marcelmay provided in SmtpServerTest.testSendAndWaitForIncomingMailsInBcc should work for your use case.

**Comment by keirlawson** [comment]
Apologies for my slowness to respond, I am using version 1.4.1 as the project in question is Java 6. Unfortunately I haven't had time yet to replicate on a newer version, will try to do that as soon as possible and update the issue

**Comment by buildscientist** [comment]
@keirlawson No worries just wanted to follow up with you. GreenMail 1.5.x requires Java 7 or above.

**Comment by keirlawson** [comment]
Ok so @marcelmay's suggested test does pass when I run it in my current project (Java 6/Greenmail 1.4.1), which suggests to me that the issue is something to do with the way the emails are being created by our system (we are using Apache Commons Email)

**Comment by keirlawson** [comment]
So this fails for me on the above setup (using Commons email 1.4):

```js
    @Test
    public void testSendAndWaitForIncomingMailsInBcc() throws Throwable {
        // Create a test email with 2 BCC
        String subject = GreenMailUtil.random();
        String body = GreenMailUtil.random();

        final Email email = new SimpleEmail();
        email.setHostName(greenMail.getSmtp().getServerSetup().getBindAddress());
        email.setSmtpPort(greenMail.getSmtp().getServerSetup().getPort());
        email.setFrom("from@localhost");
        email.setSubject(subject);
        email.setMsg(body);
        email.addBcc("bcc1@localhost", "bcc2@localhost");
        email.addTo("test@localhost");

        assertEquals(0, greenMail.getReceivedMessages().length);

        email.send();
        //GreenMailUtil.sendMimeMessage(message);

        // Expect 1 + 2 BCCs mails
        assertTrue(greenMail.waitForIncomingEmail(1500, 3));

        MimeMessage[] emails = greenMail.getReceivedMessages();
        assertEquals(3, emails.length);
    }
```

**Comment by marcelmay** [comment]
@keirlawson:

It seems Apache Commons Email has an unfortunate and error prone API:

[Email.addBcc(String email, String name)](https://commons.apache.org/proper/commons-email/javadocs/api-release/org/apache/commons/mail/Email.html#addBcc(java.lang.String,%20java.lang.String))
and
[Email.addBcc(String ... emails)](https://commons.apache.org/proper/commons-email/javadocs/api-release/org/apache/commons/mail/Email.html#addBcc(java.lang.String...))
are easily confused. The first method should have the better name like Email.addBccWithName(...).

Using an array will make the test run successfully:
`email.addBcc( new String[]{"bcc1@localhost", "bcc2@localhost"});`

I'm closing the issue.

Cheers,
Marcel
