### ISSUE TITLE
Support UTF-8 non ascii characters on email address (based on rfc6531)

### ISSUE THREAD

**Issue by ecrisostomo** [greenmail-mail-test/greenmail#170]
Greenmail server will return a `com.sun.mail.smtp.SMTPAddressFailedException: 501 Malformed email address.` when attempting to send an email with UTF-8 non ascii characters. 

This happens when sending, for example, an email to an address like this: 用户@例子.广告

I see an initial change that needs to happen and that is when constructing the `com.icegreen.greenmail.mail.MailAddress` object, where the `InternetAddress` needs to be instantiated the following way to skip the strict validation that is based on rfc822:

```java
InternetAddress address = new InternetAddress();
address.setAddress(str);
```

Some loosened up validation might need to be used to make sure that the server still doesn't take just any string as a valid email.

**Comment by camann9** [comment]
Feel free to send a pull request with some reasoning on what validation is
still present and what parts of the valuation have been relaxed.

**Comment by ecrisostomo** [comment]
Yeah, planning to work on that!
