### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by bluedoo** [greenmail-mail-test/greenmail#176]
Using `@Test(timeout=1000)` the max I can make `x` is `200`. In other words, I can only send a maximum of 200 emails per second. I think it should be closer to 4000 emails per second without async threading in order to be competitive

```
int x = 200;
for (int i = 0; i < x; i++) {
     ...
     Transport.send(message);
}
```

**Comment by camann9** [comment]
Feel free to profile greenmail and find out what is taking time. Are you
sure it's not Javamail on the client side? What happens if you use multiple
threads on the client side?

**Comment by buildscientist** [comment]
@bluedoo Can you clarify what you mean by "competitive"?  GreenMail is a testing tool - it isn't meant to be used as a production SMTP/IMAP/POP3 service.

@camann9 Probably want to be careful about using multiple threads to handle Transport based connections - see [Thread safety in JavaMail](http://stackoverflow.com/questions/12732584/threadsafety-in-javamail#answer-12733317) for more details

**Comment by camann9** [comment]
As Youssuf said, greenmail is not a production system and we haven't
traditionally cared much about performance (as long as it's able to receive
a few mails per second). That being said, if you find simple fixes to make
it faster, feel free to send a pull request.
On the subject of thread safety: that should be fine as long as multiple
connections (transports) are used.
