### ISSUE TITLE
have a way to get all sent emails with the war deployment ?

### ISSUE THREAD

**Issue by tmeedend** [greenmail-mail-test/greenmail#180]
Hi,

I have deployed greenmail war on my tomcat. I am using it as a fake smtp server so that my other webapps can send emails without sending real ones to my customers.

Is there a way to see all the emails which have been sent without providing a user ? This way I could be sure which emails are sent without specifying any user. It would be very useful for functional tests.

Thank you very much for your help.

**Comment by buildscientist** [comment]
@tmeedend Hello - as of now no. A RESTful API which could potentially provide this information is in the works - see issue #108 for more details.
