### ISSUE TITLE
Remote access to received emails

### ISSUE THREAD

**Issue by longtimeago** [greenmail-mail-test/greenmail#182]
Good day!
I love the lib as it is containerized :)
And I will love it even more if the following example could be covered in some way.
Consider components:
- Integration Test - IT  (host PC)
- Application Under Test - AUT (container A)
- Greenmail - GM (container B)

Trivial use case:
1) IT triggers email to AUT
2) AUT sent email to GM
3) IT checks GM for new emails and asserts them.

Is there any way to manage the 3td point? In other words,
Is there any way to access stored emails in containerized Greenmail from the host machine?
Does Greenmail expose any remote API for that? (jmx, REST ... )

Thanks in advance!

**Comment by camann9** [comment]
You can use IMAP?

**Comment by buildscientist** [comment]
@longtimeago Hi there - thanks for the props on GreenMail. 

Unfortunately the RESTful API is still under development - see issue #108 for more details. 

As @camann9 mentioned you can use the IMAP protocol.

**Comment by longtimeago** [comment]
@buildscientist Alright ... as I see, #108 is opened a year ago ... so, we should not expect the feature soon :)
Thus, thanks to @camann9 suggestion, will try to use IMAP

Have a nice day!
