### ISSUE TITLE
support search by TEXT

### ISSUE THREAD

**Issue by rjfioravanti** [greenmail-mail-test/greenmail#184]
It seems that search commands are not really supported, maybe just the UID variant of search? Haven't tried the message-sequence version...

Example command I am interested in

UID SEARCH CHARSET US-ASCII TEXT "query"

According to RFC 3501, this is valid command syntax, and should search for messages matching the term "query" in header or body of the message.

When I try this currently, I get the following

WARNING: Ignoring not yet implemented search command 'CHARSET'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.CHARSET
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:67)
	at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:68)
	at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:53)
	at com.icegreen.greenmail.imap.commands.UidCommand.doProcess(UidCommand.java:42)
	at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:57)
	at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98)
	at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51)
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:69)
	at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marcelmay** [comment]
@rjfioravanti , a good overview of currently implemented search is [SearchKey](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SearchKey.java).

We extend GreenMail on demand - is there any other particular search you're interested in?

Relates to #20 .

**Comment by rjfioravanti** [comment]
Sorry for the delay replying. I will also need support searching UTF-8 CHARSET, and possibly more granularity on what to search than just "TEXT". The search command also has this interesting quirk where under some circumstances we have to send a literal

e.g. 
UID SEARCH CHARSET UTF-8 TEXT {5}

Then wait for server response, before we send the 5 bytes

**Comment by tbelaire** [comment]
CHARSET is likely low priority, as it's possible to leave it out.

Would an implementation of TEXT along [these][1] lines look ok to you?

**Comment by marcelmay** [comment]
@tbelaire : thx, I'll pull in your lines and add a test.

Adding CHARSET seems a bit more tricky:
UID SEARCH CHARSET UTF-8 TEXT {9}\r\nSome Text

**Comment by marcelmay** [comment]
FYI, current work is in branch [issue/184-support-search-by-text](https://github.com/greenmail-mail-test/greenmail/tree/issue/184-support-search-by-text)

**Comment by marcelmay** [comment]
@rjfioravanti 
Let me know if search and the continuation behaviour (when sending the actual bytes) works for you - [tests](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/imap/commands/ImapProtocolTest.java#L354) seem to run ok.

If it fails, can you give me the relevant verbose output of GreenMail, enabled in tests via
`GreenMailRule greenMail = new GreenMailRule(ServerSetup.verbose(ServerSetupTest.SMTP_IMAP));`...

**Comment by rjfioravanti** [comment]
Hi Marcel. I'm not sure we have bandwidth at the moment to link in head source and test. We are currently only pulling in release binaries. When you publish the next version with this change, we will probably update our release and give it a try. If it still isn't working we can try to submit a patch to fix it for us. Thanks!

**Comment by marcelmay** [comment]
I'm closing this issue now, for the upcoming 1.5.4 release.
