### ISSUE TITLE
Support SMTP AUTH command with PLAIN mechanism

### ISSUE THREAD

**Issue by rjfioravanti** [greenmail-mail-test/greenmail#189]
most SMTP clients will be written to authenticate a user over the connection. 

The EHLO command should return the fact that AUTH extension is supported. Example EHLO from yahoo below
ehlo 127.0.0.1
250-smtp.mail.yahoo.com
250-PIPELINING
250-SIZE 41697280
250-8 BITMIME
250 AUTH PLAIN LOGIN XOAUTH2 XYMCOOKIE

To start, it would be reasonable to just return, the following, indicating that the host supports username/password auth
250 AUTH PLAIN

Then of course beyond modifying EHLO response, the actual AUTH command needs to be supported. the command is documented in https://tools.ietf.org/html/rfc4954

Example auth command
AUTH PLAIN dGVzdAB0ZXN0ADEyMzQ=

The garbled text there is username/password concatenated with null delimiters and then encoded as base64. Ideally the server would then assert this is a user that was configured in GreenMail#setUser

**Comment by marcelmay** [comment]
Relates to #127

**Comment by ralphtheninja** [comment]
Any progress on this? I really like this server for its simplicity and ease of configuration but missing `AUTH` command is a bummer :/

**Comment by marcelmay** [comment]
As stated above, AUTH PLAIN might be a starter. I'll try to look into this ~ next weekend.

**Comment by marcelmay** [comment]
@rjfioravanti : I changed the title and scoped it to AUTH PLAIN only. For a start.

@ralphtheninja : Can you provide feedback? So far I ran only some junit tests, using SMTP protocol directly and via `Transport.send(msg, user, pwd)`.

**Comment by marcelmay** [comment]
Additional note: GreenMail SMTP does not enforce AUTH at the moment, but if a client sends AUTH GreenMail SMTP will authenticate agains a created user. See test example [SmtpServerTest#testAuth](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/test/SmtpServerTest.java#L160).

**Comment by ralphtheninja** [comment]
> @ralphtheninja : Can you provide feedback? So far I ran only some junit tests, using SMTP protocol directly and via Transport.send(msg, user, pwd).

Definitely. Trying to build latest master (via `mvn clean install -Pdocker`) but run into some problems:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test (default) on project greenmail-parent: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test failed: A required class was missing while executing org.apache.maven.plugins:maven-failsafe-plugin:2.20:integration-test: javax/xml/bind/JAXBException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-failsafe-plugin:2.20
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/lms/.m2/repository/org/apache/maven/plugins/maven-failsafe-plugin/2.20/maven-failsafe-plugin-2.20.jar
[ERROR] urls[1] = file:/home/lms/.m2/repository/org/apache/maven/surefire/maven-surefire-common/2.20/maven-surefire-common-2.20.jar
[ERROR] urls[2] = file:/home/lms/.m2/repository/org/apache/maven/surefire/surefire-booter/2.20/surefire-booter-2.20.jar
[ERROR] urls[3] = file:/home/lms/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[4] = file:/home/lms/.m2/repository/junit/junit/4.12/junit-4.12.jar
[ERROR] urls[5] = file:/home/lms/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
[ERROR] urls[6] = file:/home/lms/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[7] = file:/home/lms/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[8] = file:/home/lms/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[9] = file:/home/lms/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[10] = file:/home/lms/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[11] = file:/home/lms/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/home/lms/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/home/lms/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
[ERROR] urls[14] = file:/home/lms/.m2/repository/org/apache/maven/surefire/surefire-api/2.20/surefire-api-2.20.jar
[ERROR] urls[15] = file:/home/lms/.m2/repository/org/apache/maven/surefire/surefire-logger-api/2.20/surefire-logger-api-2.20.jar
[ERROR] urls[16] = file:/home/lms/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : javax.xml.bind.JAXBException
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

I'm no java expert, but it seems I'm missing something.

**Comment by marcelmay** [comment]
Are you using JDK9/10/11? Looks like JDK 9 modularization side effect.

Try adding `--add-modules java.xml.bind` to the Maven options environment MAVEN_OPTS, 
eg for bash via `export MAVEN_OPTS="$MAVEN_OPTS --add-modules java.xml.bind"`.

**Comment by ralphtheninja** [comment]
> Are you using JDK9/10/11? Looks like JDK 9 modularization side effect.

Aye, 11.

> Try adding --add-modules java.xml.bind to the Maven options environment MAVEN_OPTS,
> eg for bash via export MAVEN_OPTS="$MAVEN_OPTS --add-modules java.xml.bind".

Worked like a charm. Thanks for assistance! Will test a bit and get back to you.

**Comment by ralphtheninja** [comment]
@marcelmay I can login with smtp using DeltaChat now! :smile:

**Comment by marcelmay** [comment]
Good news, and thx for the feedback.

So I'll close this and will probably build a release [1.5.8](https://github.com/greenmail-mail-test/greenmail/milestone/14?closed=1) ~ tomorrow.

**Comment by ralphtheninja** [comment]
> So I'll close this and will probably build a release 1.5.8 ~ tomorrow.

Sounds good!
