### ISSUE TITLE
problems with parallel sending and retrieving

### ISSUE THREAD

**Issue by baubakg** [greenmail-mail-test/greenmail#190]
Hi There,

I was unable to find an active DL for this so I post here. 

I have created a set of methods for managing emails. I am using GreenMail to make sure my tests are ok. Befor emy tests I instantiate a local GreenMail server:

       private GreenMail mailServer;
       private GreenMailUser user;

       @BeforeClass
    public void setUp() { 
      Security.setProperty("ssl.SocketFactory.provider",DummySSLSocketFactory.class.getName());

        mailServer = new GreenMail(ServerSetupTest.SMTPS_IMAPS);

        mailServer.start();
        String host = "localhost";
        String username = "test";
        String password = "mypassword";
        String userAddrsss = username + "@" + host;

        // create user on mail server
        user = mailServer.setUser(userAddrsss, username, password);}

When sending a message I simply create my MimeMessage and send it:
`user.deliver(message);`

My methods perform a standard javax mail:

            Properties props = new Properties();

        try {
            // Connect to the server
            //Session session = Session.getDefaultInstance(props, null);
            props.setProperty("mail.store.protocol", "imaps");
            Session session = Session.getInstance(props, null);
            Store store = session.getStore("imaps");

             store.connect("localhost", 3993, "test", "mypassword");

            // open the inbox folder
            Folder inbox = store.getFolder(folder);
            inbox.open(Folder.READ_ONLY);
           
            // get a list of javamail messages as an array of messages
            Message[] l_messages = inbox.getMessages()`

My test is pretty simple. I deliver an email to the user "test", and use a normal javax.mail check to fetch the messages.

This works fine as long as I perform the test in **serial**. But when the test is executed in **parallel** (using testng's (invocationCount = 3, threadPoolSize=3) I get weird errors. Duplicate messages, no messages etc...

If I send the email without "user.deliver" the parallelism works fine.

Any suggestions are most welcome.

**Comment by marcelmay** [comment]
If you send with user.deliver, you are responsible for synchronization.

If you send via SMTP: Can you post a test reproducing the behaviour?

Thx alot!

**Comment by baubakg** [comment]
Thanks for your answer.

Could you kindly tell me how I can synchronize this?

In the meantime here, attached is a small project that shows this:
[GM_ParallelProblem.zip](https://github.com/greenmail-mail-test/greenmail/files/806232/GM_ParallelProblem.zip)

(sorry, I cannot post java files it seems)

**Comment by baubakg** [comment]
Thanks for your answer. Could you kindly share how I can perform the synchronization?

PS I will attach a zip for this. The test is in testng that allows for

**Comment by baubakg** [comment]
It seems I inadvertedly closed this issue :)

Could I have some info on how I can perform the synchronization please? (Between storing the message using user.deliver(MimeMessage) and being able to fetch it using javax.mail and standard imap protocols please?

I have added a code showing this in my comment above.

**Comment by marcelmay** [comment]
You can synchronise eg on the GreenMail instance as a lock when sending via user.deliver(MimeMessage):
```
synchronized (mailServer) {
            user.deliver(message);
}
```

See the [Java Tutorial](https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html) for sychronization details.

Another note: I think you can avoid checking if mail has arrived after user.deliver(...), as user.deliver(...) stores the mail directly...
