### ISSUE TITLE
Ignoring not yet implemented search command 'OR'

### ISSUE THREAD

**Issue by sanjeev-addagarla** [greenmail-mail-test/greenmail#193]
Trying to read an email on imap server with the below code: (Search subject with either of two Strings)

Store store = emailSession.getStore("imap");

Folder emailFolder = store.getFolder("INBOX");
      emailFolder.open(Folder.READ_ONLY);
      SearchTerm st = new OrTerm(new SubjectTerm("Request+:+NID"),new SubjectTerm("Request : NID"));
      Message[] messages = emailFolder.search(st);
      System.out.println("messages.length---" + messages.length);

**Messages.lenght is 0 and we see the below error in logs:**

Exception in logs:
1469955 WARN  mands.SearchCommandParser| Ignoring not yet implemented search command 'OR'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.OR
        at java.lang.Enum.valueOf(Unknown Source)
        at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:68)
        at com.icegreen.greenmail.imap.commands.SearchCommandParser.searchTerm(SearchCommandParser.java:87)
        at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:53)
        at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:41)
        at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:57)
        at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98)
        at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51)
        at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:71)
        at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:163)

**Comment by marcelmay** [comment]
Relates to #20

**Comment by sanjeev-addagarla** [comment]
Hi Marcel,

Can you suggest high-level changes for this enhancement, I will try to contribute OR fix it locally.

thanks

**Comment by marcelmay** [comment]
Hi @sanjeev-addagarla,

I'd start with a test.

Interesting code is [SearchCommand](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SearchCommand.java)/[SearchCommandParser](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SearchCommandParser.java) and [ImapSearchTest](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/test/commands/ImapSearchTest.java) .

Looking forward to your contribution,
Marcel

**Comment by sanjeev-addagarla** [comment]
Hi Marcel,
I have modified the below files and initial testing looks good to support this OR term enhancement.
SearchCommandParser.java
SearchKey.java
SearchTermBuilder.java

I will perform a thorough testing and update you.
Meanwhile,  I am attaching the updated source code on this bug.
[UpdatedSource.zip](https://github.com/greenmail-mail-test/greenmail/files/841669/UpdatedSource.zip)

**Comment by marcelmay** [comment]
Hi @sanjeev-addagarla ,

thanks for the preview.

Tests pass, if you change the following to avoid a NPE triggered by ImapProtocolTest in SearchCommandParser.java, line 114:

```
-					if (key.toString().contains("OR")) {
+					if (SearchKey.OR == key) {
```

Can you add a test for the OR search to eg ImapSearchTest, and then open a pull request?
Add some search conditions involving OR.

I noticed some minor issues like (probably automatic) reformatting which should be avoided - but we can discuss this on the PR.

**Comment by sanjeev-addagarla** [comment]
HI Marcel,
I keep getting the attached error while trying to clone the repo. Do I need any additional permissions?
![giterror](https://cloud.githubusercontent.com/assets/26110934/23947795/491484a8-09a6-11e7-9d5f-162f3c535e3a.png)

**Comment by sanjeev-addagarla** [comment]
Hi Marcel,

I have fixed auto-formatting issues and updated ImapSearchTest.java with couple of tests.
Pull request: https://github.com/greenmail-mail-test/greenmail/pull/194

**Comment by marcelmay** [comment]
@sanjeev-addagarla , can you look at ImapSearchTest.testSearch?

It fails:
```
java.lang.AssertionError
    at com.icegreen.greenmail.test.commands.ImapSearchTest.testSearch(ImapSearchTest.java:115)
```

**Comment by sanjeev-addagarla** [comment]
Hi Marcel,

I apologize, I am not familiar with greenmail tests(junit) and how to run it.
That's why I couldn't respond to you on PR#194.

Can you elaborate the issue you have mentioned in above comment. (what is the error you get?)
excluding the test classes, I did a full testing for OR and AND terms in our application and everything looks good.

**Comment by marcelmay** [comment]
Just run 'mvn clean test' - your test fails at given source code location.
If you look at the test, you see that it checks for text not available in the test message.

**Comment by technotronic12** [comment]
Hey, what is the status of the issue? Do you need help with it?

**Comment by sanjeev-addagarla** [comment]
Hi Eli,

Yes, can you take a look?
I have validated the changes on pull request: https://github.com/greenmail-mail-test/greenmail/pull/194 
 locally and it worked as expected. However Marcel has mentioned an issue while running the test package. I am not familiar with maven and didnt get a chance to look into it.

Thanks
SA

**Comment by marcelmay** [comment]
Any help with tests etc is very appreciated :-)

**Comment by technotronic12** [comment]
I found the problem and fixed it but I cannot push the change to Sanjeev's account:
Permission to sanjeev-addagarla/greenmail-Issue193.git denied to technotronic12.

**Comment by sanjeev-addagarla** [comment]
Hi Eli,

I have added you as a collaborator on my repo, Can you try pushing the code again?

**Comment by technotronic12** [comment]
I want to do some refactor to the search command parser and the imap search test. Please add me as a collaborator to this repo so I could contribute

**Comment by sanjeev-addagarla** [comment]
Hi Eli,
You were already added as a collaborator.

Thanks

**Comment by technotronic12** [comment]
I wrote to @marcelmay, please add me to your repo so I can push some refactoring

**Comment by marcelmay** [comment]
@technotronic12 : For refactorings, please create a pull request from current master.
That search part has grown alot and can use quite some refactorings.
