### ISSUE TITLE
Running GreenMail server on jenkins

### ISSUE THREAD

**Issue by SvetlanaKarakasheva** [greenmail-mail-test/greenmail#196]
Hello,
I have the following case. Maven project, running on Jenkins with JUnit tests that use GreenMail. The test run starts a virtual machine on another machine where we have running JBoss and browser, where Selenium tests are running remotely from Jenkins. The application that is installed in the virtual machine sends mails, which I need to catch and check in the tests on Jenkins. Is that possible to be handle by GreenMail? I've tried to setup the server by using the remote machine IP, but got:
Exception in thread "smtp:10.14.X.X:25" java.lang.IllegalStateException: Can not open server socket for smtp:10.14.X.X:25

Shall I deploy the greenMail as JBoss Service? Is it possible to receive the messages in the Jenkins test run in such case?
What solution would you propose?

**Comment by marcelmay** [comment]
Hi @SvetlanaKarakasheva!
   
GreenMail JBoss Service only supports old JBoss version <= 6, and will be retired in the next version.

A better choice is the more generic [WAR deployment](http://www.icegreen.com/greenmail/#deploy_webapp). If your application-under-test runs on JBoss, the WAR deployment would be a good choice as it is available as long as your application-under-test runs.

**Comment by buildscientist** [comment]
The other alternative is to use greenmail-standalone which you can deploy in a docker container and configure as part of a Jenkins job pre-build step.
