### ISSUE TITLE
Send mail from localhost within a junit test

### ISSUE THREAD

**Issue by JensPiegsa** [greenmail-mail-test/greenmail#197]
Newbie question:
Beside simulating email delivery and recieving, is it actually possible to send a real mail from e.g. `example@localhost.com` to `someaccount@gmail.com` via smtp with GreenMail within a junit test? Or is this only possible with another server, or the `standalone` GreenMail?

Or maybe the targetted server blocks my mails?

**Comment by buildscientist** [comment]
@JensPiegsa No it's not possible as GreenMail effectively acts as a closed loop. When your client (email app, test code etc) interfaces with GreenMail's SMTP server - the email is automatically dropped into the users mailbox - assuming the user is defined in GreenMail. 

Is there any reason why you're trying to relay to an actual SMTP server?

**Comment by buildscientist** [comment]
The code in question that handles this available here - [SmtpManager.java]( https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/smtp/SmtpManager.java#L126-L146)

**Comment by JensPiegsa** [comment]
Thanks a lot for the clarification. My use case: I would like to produce content alterations based on html templates for a quick visual check in multiple mail clients.

**Comment by buildscientist** [comment]
Makes sense now. 

One option you might consider would to be configure your mail clients to pull the emails down via POP3/IMAP after the client generating the email/html templates relays it to GreenMail SMTP. 

On a side note if you're just looking to do a quick visual check for "look and feel" in multiple email clients I highly recommend [Litmus.com](http://litmus.com). Not a free service but they cover the majority of email clients (Lotus Notes included) on different platforms and devices. 

Note I am not employed by Litmus nor do I gain anything financially by recommending them to you - but tell them the buildscientist sent you :)

**Comment by JensPiegsa** [comment]
Looks interesting. I'll take a look at it. :-)
