### ISSUE TITLE
SearchCommandParser, npe, v 1.5.4

### ISSUE THREAD

**Issue by p-ledenev** [greenmail-mail-test/greenmail#202]
Line 92 com.icegreen.greenmail.imap.commands.SearchCommandParser
`if (b.expectsParameter() && key.isCharsetAware() && null != charset && next == CHR_SPACE) {`
**b** is still null after
```
SearchKey key = SearchKey.valueOf(keyValue);
 if (SearchKey.NOT == key) {
     negated = true;
 } else {
     b = SearchTermBuilder.create(key);
 }
```

**Comment by marcelmay** [comment]
I think this is a duplicate of #201

**Comment by marcelmay** [comment]
@p-ledenev , let me know if newest 1.5.5 release still shows the issue - thx!
