### ISSUE TITLE
Reply-To header in SMTP

### ISSUE THREAD

**Issue by eflood** [greenmail-mail-test/greenmail#204]
When parsing an incoming SMTP message, the SimpleMessageAttributes class attempts to parse a Header called "Reply To". I Believe the the correct name is "Reply-To"

The result is that when the message is retrieved via IMAP the message.getReplyTo() method does not work as expected.

try {
            replyTo = part.getHeader("Reply To");
        } catch (MessagingException me) {
//            if (DEBUG) getLogger().debug("Messaging Exception for getHeader(Reply To): " + me);
        }

I can submit a pull request to fix if required.

Thanks

Eoin.

**Comment by marcelmay** [comment]
Hi @eflood,

a pull request including test would be very cool. Please try to keep the modifications to a minimum (no auto formatting). Thx alot!

**Comment by marcelmay** [comment]
Thx alot!
