### ISSUE TITLE
Update embedded default certificate in greenmail.jks 

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#206]
It's outdated and uses SHA-1.
Also ~~update~~remove the hard coded one in DummySSLServerSocketFactory.java .

**Comment by chriswhite199** [comment]
Pull Request #217 has been opened for review

**Comment by buildscientist** [comment]
@chriswhite199 
Thanks for the PR. Any chance we could get the byte stream for the JKS generated? 

@marcelmay is that something we can do on init given that we're now generating a new JKS per build?

**Comment by marcelmay** [comment]
@buildscientist  : I think I'll throw out the byte stream, and always load it from greenmail.jks. I believe it is a leftover from back when there was no greenmail.jks.

**Comment by buildscientist** [comment]
@marcelmay Makes sense - although I like the idea of having a backup in case for whatever reason the JKS can't be loaded. For example if the plugin introduces a bug and starts generating bad JKS - GreenMail won't load.

**Comment by marcelmay** [comment]
That case - broken jks - should be caught by our tests which send/receive via SMTPS/POP3S/SMTPS.

Actually I believe the fallback never was tested...

**Comment by buildscientist** [comment]
Agreed but even in that case our users will either have to upgrade to the latest version to get a fix or override the build process. 

I still think that the fallback process should be implemented. For the time being we can close out this issue and create a new fallback process (with tests) as an enhancement.

**Comment by marcelmay** [comment]
I'll change the certificate validity to the max of 825 days.
