### ISSUE TITLE
Return Content-ID header in bodystructure response

### ISSUE THREAD

**Issue by seguljacg** [greenmail-mail-test/greenmail#209]
4th part of the bodystructure response should be (see RFC 3501)

"body id
            A string giving the content id as defined in [MIME-IMB]."

Currently, nothing is being returned.

https://github.com/greenmail-mail-test/greenmail/blob/b3d5dce0a5aa019932f879250744d0b00fc37eec/greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java#L517

**Comment by marcelmay** [comment]
@seguljacg , do you have a test case/test email?

**Comment by marcelmay** [comment]
Please reopen if it still fails in upcoming 1.5.7 .  I was not able to reproduce it that by a test, but as you mentioned it was obviously missing in the code for certain cases.
