### ISSUE TITLE
SimpleMessageAttributes parsing of personal email addresses containing quoted commas

### ISSUE THREAD

**Issue by chriswhite199** [greenmail-mail-test/greenmail#213]
When trying to replay raw email messages through GreenMail, i've come across the following stack trace error, which relates to the fact that the From email address in my raw email file has a 'personal' email component to it, and that component contains a comma:

    From: "Test, User" <test@localhost>

Here's the stack trace:

```
2017-10-04 11:00:44.305  WARN 29152 --- [127.0.0.1:55889] c.i.g.store.SimpleMessageAttributes      : Can not parse address "Test - ignored.

javax.mail.internet.AddressException: Missing '"'
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:884)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:655)
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:115)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.parseAddress(SimpleMessageAttributes.java:371)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.parseAddress(SimpleMessageAttributes.java:396)
	at com.icegreen.greenmail.store.SimpleMessageAttributes.addAddressToEnvelope(SimpleMessageAttributes.java:357)
```

The InternetAddress constructor happily accepts the string:

    new InternetAddress("\"Test, User\" <test@localhost>")

The issue appears to be the comma tokenization used in the following, which doesn't account for quoted values:

```
    /**
     * Parses a String email address to an IMAP address string.
     */
    private String parseAddress(String address) {
        int comma = address.indexOf(',');
```

**Comment by marcelmay** [comment]
Thx for reporting and analysing this issue @chriswhite199.

I will investigate the issue this weekend - any PR welcome (for test case, or complete fix).

**Comment by chriswhite199** [comment]
I think you just need to use the `InternetAddress.parseHeader(address, true)` method use the default rules and then for each InternetAddress returned in the array, call the `getAddress()` method - i'll take a look and raise a PR if i can make it work

**Comment by chriswhite199** [comment]
You can trigger the failure by updating the `GreenMailUtilTest.testSendTextEmailTest` as follows:

```
@Test
    public void testSendTextEmailTest() throws Exception {
        GreenMail greenMail = new GreenMail(ServerSetupTest.SMTP_IMAP);
        try {
            greenMail.setUser("foo@localhost", "pwd");
            greenMail.start();
            // add personal names with commas:
            GreenMailUtil.sendTextEmail("\"Foo, Bar\" <foo@localhost>", "\"Bar, Foo\" <bar@localhost>",
                    "Test subject", "Test message", ServerSetupTest.SMTP);
```

**Comment by chriswhite199** [comment]
PR #214

**Comment by marcelmay** [comment]
Thx alot for the PR, @chriswhite199 !
