### ISSUE TITLE
Upgrade to JavaMail 1.6

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#216]
- Maven dependencies
- Javadoc links (pom.xml)
- Check [release note](https://javaee.github.io/javamail/) for further actions

**Comment by KyleRogers** [comment]
When upgrading you should also consider changing to Jakarta Mail because the JavaMail project transitioned to the Eclipse Foundation, see https://eclipse-ee4j.github.io/javamail/

The artifact coordinates changed to
```
<dependencies>
            <dependency>
                <groupId>com.sun.mail</groupId>
                <artifactId>jakarta.mail</artifactId>
                <version>1.6.3</version>
            </dependency>
        </dependencies>
```

**Comment by marcelmay** [comment]
Thx, @KyleRogers !
