### ISSUE TITLE
Support for JUnit 5

### ISSUE THREAD

**Issue by rweisleder** [greenmail-mail-test/greenmail#219]
JUnit 5 does not support `@Rule` anymore: http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4
Instead Greenmail should support an extension which implements the same behaviour as `GreenMailRule`.

JUnit 5 requires Java 8, so at least the new extension must have the compile source 1.8.

**Comment by voplex95** [comment]
Hi,
Seems like milestone 1.6 is far from over.
https://github.com/greenmail-mail-test/greenmail/milestone/4
If support for JUnit 5 is considered to be implemented, maybe it could be released sooner as a separate version.
Would really appreciate it.

**Comment by marcelmay** [comment]
You could try [latest 1.6-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/). It contains #241 , a new [GreenMail module](greenmail/tree/master/greenmail-junit5) providing Junit5 support.

**Comment by kedarpanse** [comment]
Just checking if is this ready for prime time yet?

**Comment by Ristop** [comment]
Any ideas when Junit 5 support will be released?

**Comment by matusmala** [comment]
It would be great if you release the https://github.com/greenmail-mail-test/greenmail/tree/master/greenmail-junit5. It's working fine. But the examples are realy bad!

**Comment by derTobsch** [comment]
We upgraded to Spring Boot 2.2.x with junit5 support and now greenmail does not work with junit5. That is quite sad. Is there a way to help?

**Comment by marcelmay** [comment]
Will try to do an initial release candidate for 1.6 containing greenmail-junit5 this weekend.

Things for discussion, any feedback appreciated:
- Migrate completely from junit4 to junit5 for GreenMail 1.6, or keep current split (core using junit4 and greenmail-junit5?

**Comment by derTobsch** [comment]
This will be a breaking change so I would go to 2.0 with junit5 only support and further provide for some time the 1.x. 
Why go completely to junit5? Because with the vintage and the Jupiter engine the applications can have junit4 and junit5 tests at the same time. That's how I did it in my application. Everything except greenmail tests are junit5

**Comment by marcelmay** [comment]
Thx, @derTobsch .

I really want to cut the knot of compile scoped dependency of greenmail-core to (any) test framework, to make the core more flexible and to avoid this kind (junit4/junit5... testng) depdency issues.

GreenMail 1.6 : 
* Clone JUnit4 GreenMailRule to new greenmail-junit4 module and junit4 package, and mark original GreenMailRule as deprecated
* Move integration tests (integration by starting GreenMail instance) from greenmail-core to new greenmail-testsuite module and start using junit5 integration

GreenMail 1.7 :
* Remove GreenMailRule from greenmail-core, greenmail-core will only have test-scoped junit dependency

GreenMail 2.0:
* Think of dropping greenmail-junit4 (depending on usage stats)

**Comment by marcelmay** [comment]
@derTobsch  : Updated current [1.6-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/) if you want to give that a try. An RC0 should be coming in the next few days (want to update JavaMail for that).

**Comment by derTobsch** [comment]
Thanks for your Feedback and the Snapshot. I hope I have the time this week to test it but I feel that it will be the next week. :-/

**Comment by rkcpi** [comment]
Any updates on this? Not having junt5 support blocks me right now from using GreenMail at all...

**Comment by derTobsch** [comment]
Hey @marcelmay,
I tried the greenmail 1.6.0-SNAPSHOT and it looks good from here see https://github.com/synyx/urlaubsverwaltung/pull/1267.

I am happy to help you out if you need some help.

**Comment by marcelmay** [comment]
Thx for the feedback, @derTobsch . I'm going to release 1.6 now.
