### ISSUE TITLE
GreenMail.waitForIncomingEmail(...) waits twice the requested time

### ISSUE THREAD

**Issue by smccants** [greenmail-mail-test/greenmail#220]
Working on speeding up some of our tests and I noticed that when we call waitForIncomingEmail(time, number) and we are desiring a time out (i.e. the code under test should *not* send an email), waitForIncoingEmail() waits twice as long as our code requests.  For example:

`mailServer.waitForIncomingEmail(10000, 1);`

will time out after 20000ms. 

This was seen with GreenMail 1.5.5.

**Comment by smccants** [comment]
Test case written for JUnit4 with Hamcrest.  Reproduces the problem pretty reliably:

```
import com.icegreen.greenmail.util.GreenMail;
import com.icegreen.greenmail.util.ServerSetup;
import org.junit.Test;

import static org.junit.Assert.*;
import static org.hamcrest.Matchers.*;

/**
 * Simple test case to reproduce GreenMail problem.
 * 
 * @author smm
 */
public class GreenMailTest {
    
    @Test
    public void greenMailWaitsTooLongTest() {
        GreenMail greenMailServer = new GreenMail(new ServerSetup(10100, "localhost", ServerSetup.PROTOCOL_SMTP));
        greenMailServer.start();
        long start = System.currentTimeMillis();
        boolean mailReceived = greenMailServer.waitForIncomingEmail(10000, 1);
        long finish = System.currentTimeMillis();
        System.out.println("Time spent = "+(finish - start));
        assertThat(mailReceived, is(false));
        assertThat(finish - start, is(lessThan(11000l)));
        assertThat(finish - start, is(greaterThan(9000l)));
    }
}
```

**Comment by marcelmay** [comment]
Hi @smccants!

Thanks alot for providing a test.

That is strange: The test runs fine, even when looping the wait part.
The timeout works with less than 0.1% deviation from the specified timeout (MacOs 10.13.1  / Oracle JDK 1.8.0_151 / GreenMail 1.5.6).

What's your OS and JDK version?
What's the OS current load?

**Comment by marcelmay** [comment]
@smccants : It seems to occur pretty randomly. Just had the test fail for the first time.

**Comment by marcelmay** [comment]
Under unfortunate conditions - Object.wait(...) with early interruption before mail arrival - the wait can take twice as long.

**Comment by smccants** [comment]
Thanks for looking into this.  It was failing very reliably for me and I've rarely seen Object.wait(...) go twice as long before, but it certainly can be unreliable.  You'd think in this day and age we would have computers and software that could count reliably. =)

Thanks again for looking into it.
