### ISSUE TITLE
Migrate from hamcrest to assertj

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#222]
Migrate from hamcrest to [assertj](http://joel-costigliola.github.io/assertj/index.html).

Summary of AssertJ vs Hamcrest:
https://www.blazemeter.com/blog/hamcrest-vs-assertj-assertion-frameworks-which-one-should-you-choose

**Comment by ishanarora04** [comment]
Hey, Can I pick this issue ?

**Comment by marcelmay** [comment]
Sure! Thx a million!

**Comment by marcelmay** [comment]
Solved by PR #335 . Thanks again, @ishanarora04 !
