### ISSUE TITLE
Could not start mail server imaps in Docker container

### ISSUE THREAD

**Issue by longtimeago** [greenmail-mail-test/greenmail#223]
Good day!
We've faced with weird instability - pretty often imap server can't start with following log:

```java
0       INFO  GreenMailStandaloneRunner| Starting GreenMail standalone using [
ServerSetup{port=3025, bindAddress='0.0.0.0', protocol='smtp', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=1000}, 
ServerSetup{port=3465, bindAddress='0.0.0.0', protocol='smtps', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=1000}, 
ServerSetup{port=3110, bindAddress='0.0.0.0', protocol='pop3', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=1000}, 
ServerSetup{port=3995, bindAddress='0.0.0.0', protocol='pop3s', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=1000}, 
ServerSetup{port=3143, bindAddress='0.0.0.0', protocol='imap', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=1000}, 
ServerSetup{port=3993, bindAddress='0.0.0.0', protocol='imaps', readTimeout=-1, connectionTimeout=-1, writeTimeout=-1, serverStartupTimeout=1000}]
Exception in thread "main" java.lang.IllegalStateException: Could not start mail server imaps:0.0.0.0:3993, try to set server startup timeout > 1000 via ServerSetup.setServerStartupTimeout(timeoutInMs)
```

We start container from `greenmail/standalone:1.5.2` image with following parameters 
`GREENMAIL_OPTS=-Dgreenmail.setup.test.all -Dgreenmail.hostname=mailmock -Dgreenmail.auth.disabled -Dgreenmail.verbose`

Is there any way to increase startup server timeout via system property?
Could we add some more logs to see what is the cause of failed start?

Thanks in advance!
Paul

**Comment by marcelmay** [comment]
Unfortunately there is no configurable timeout (yet).

* Try latest 1.5.6 - since 1.5.3, you can pass ENV variables to Docker image (#179 , since 1.5.3)
* Run standalone interactively to see output:
```
GREENMAIL_OPTS="-Djava.net.preferIPv4Stack=true -Dgreenmail.setup.test.all -Dgreenmail.hostname=mailmock -Dgreenmail.auth.disabled -Dgreenmail.verbose"
docker run -t -i --rm -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995 \
    -e GREENMAIL_OPTS="${GREENMAIL_OPTS}" \
    greenmail/standalone:1.5.6
```
* Is```mailmock``` DNS resolvable? Maybe just try ```0.0.0.0```?

**Comment by longtimeago** [comment]
@marcelmay thanks for suggestions! We will try latest version but not sure if it will help.
Most probably, host appears to be under heavy load, thus, greenmail simply can't finish startup in 1s.
So, it would be very nice to expose timeout as a system property :)

> Is mailmock DNS resolvable?

@marcelmay Yes, it is :) we run docker-compose

**Comment by marcelmay** [comment]
@longtimeago : Can you try latest [greenmail/standalone:1.6.0-SNAPSHOT docker image](https://hub.docker.com/r/greenmail/standalone/tags/) or GreenMail 1.6.0-SNAPSHOT? 

The default timeout of 1000ms can be overridden now via -Dgreenmail.startup.timeout=<TIMEOUT_IN_MILLISECONDS> .

**Comment by longtimeago** [comment]
@marcelmay thank you very much! This is exactly what we need :+1: 
Hope to see new release with this parameter soon. 
Have a nice holidays! :)

**Comment by marcelmay** [comment]
Closing the issue, as I'm about to release 1.5.7 containing the mentioned fix.

**Comment by longtimeago** [comment]
Thanks a lot!
