### ISSUE TITLE
Error in getReceivedMessagesForDomain(String domain) in GreenMail.class

### ISSUE THREAD

**Issue by sunmeplz** [greenmail-mail-test/greenmail#228]
In getReceivedMessagesForDomain(String domain)
```
   @Override
    public MimeMessage[] getReceivedMessagesForDomain(String domain) {
        List<StoredMessage> msgs = managers.getImapHostManager().getAllMessages();
        List<MimeMessage> ret = new ArrayList<>();
        try {
            for (StoredMessage msg : msgs) {
                String tos = GreenMailUtil.getAddressList(msg.getMimeMessage().getAllRecipients());
                if (tos.toLowerCase().contains(domain)) {
                    ret.add(msg.getMimeMessage());
                }
            }
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
        return ret.toArray(new MimeMessage[ret.size()]);
    }
```
I don't know it is a bug or feature, but this expression  if (tos.toLowerCase().contains(domain)) cause bug when you have similar names lile name@domain and somename@domain.If you send one message for each address this results unexpected message count for name@domain as it additionaly got somename@domain message

**Comment by marcelmay** [comment]
Hi @sunmeplz !

For your example ```getReceivedMessagesForDomain('domain')``` , I'd expect
all messages mails for
* somename@domain
* name@domain

an no mails for users of other domains like
* name@other-domain
