### ISSUE TITLE
Is there any way to connect to greenmail api that runs on another host?

### ISSUE THREAD

**Issue by dtsvirkun** [greenmail-mail-test/greenmail#229]
We run greenmail server on other another VM, we can use it as mail box server, but we want to create user on running server, is there any way to connect to already running stadlalone server (jar or inside docker) and play with users on it?

**Comment by marcelmay** [comment]
Hi @HDimka!

GreenMail has currently no remote admin api (but there is a feature request for one #108).

Have you tried the option "-Dgreenmail.auth.disabled" , would that work for you? Any pwd gets accepted, and users should be auto created.
