### ISSUE TITLE
Can not run roundcube docker-compose

### ISSUE THREAD

**Issue by ahmedmohiduet** [greenmail-mail-test/greenmail#238]
I am facing error msg: "roundcube_1  | /bin/sh: /run.sh: not found" "roundcube_roundcube_1 exited with code 127"

![image](https://user-images.githubusercontent.com/3110101/36667150-23fc95ec-1b17-11e8-976d-683b1780e961.png)

How can I get around this issue?

**Comment by marcelmay** [comment]
@ahmedmohiduet , can you provide the full output?

Any change when you do run docker commands [directly](https://github.com/greenmail-mail-test/greenmail/tree/master/greenmail-docker/clients/roundcube#how-to-run-with-docker-instead-of-docker-compose)  (without docker-compose)?

**Comment by marcelmay** [comment]
Running `docker-compose up --build` works, please reopen with details how you started docker-compose/how to reproduce.
