### ISSUE TITLE
Retriever using SMTPS TLS

### ISSUE THREAD

**Issue by javydreamercsw** [greenmail-mail-test/greenmail#243]
Trying code as follows:

```
try (Retriever retriever = new Retriever(mailServer.getSmtps()))
    {
         Message[] messages = retriever.getMessages(email, password);
    if (messages != null)
    {
      for (Message m : messages)
      {
        TestCaseUtils.originalSystemOut.println("Subject: " + m.getSubject());
        TestCaseUtils.originalSystemOut.println("Sent Date: "
                + m.getSentDate());
        TestCaseUtils.originalSystemOut.println("From: "
                + Arrays.toString(m.getFrom()));
        TestCaseUtils.originalSystemOut.println("Subject: " + m.getContent());
      }
    }
    else
    {
      TestCaseUtils.originalSystemOut.println("No emails for: " + email);
    }
    }
```
Gives me an error on `Message[] messages = retriever.getMessages(email, password);` about invalid provider.

I create the server as suggested:

```
Security.setProperty("ssl.SocketFactory.provider",
            DummySSLSocketFactory.class.getName());
mailServer = new GreenMail(ServerSetupTest.SMTPS);
    mailServer.start();
```

Receiving the messages li below gives no issues:

`Message[] messages = mailServer.getReceivedMessages();`

**Comment by marcelmay** [comment]
Retriever works by using the mail protocols (IMAP or POP3) for retrieving mails, and therefore works remotely.

A `mailServer.getReceivedMessages()` directly accesses the server instance (and won't work remotely).

Regarding your example:
* Start GreenMail using SMTPS (for sending) and IMAPS for retrieving email:
   `mailServer = new GreenMail(ServerSetupTest.SMTPS_IMAPS);`
* Use imap server when retrieving:
   `try (Retriever retriever = new Retriever(mailServer.getImaps()))`
