### ISSUE TITLE
Web IF in standalone docker

### ISSUE THREAD

**Issue by x29a** [greenmail-mail-test/greenmail#244]
Hi there and thanks for a great software!

Is it possible to get a web interface from the docker standalone container just like the JBoss JMX interface?

Or any other management interface besides SSH or setting up a full mailclient?

thanks!

**Comment by marcelmay** [comment]
Hi @x29a!

I recommend to use eq squirrelmail or rainloop (eg via docker compose).
GreenMail uses some [web ui docker images](../tree/master/greenmail-docker/clients) for testing.

Adding a mail web UI to GreenMail would be reinventing the wheel, and is out of scope.
You can use any IMAP client and connect to GreenMail.

There is a plan to add an admin mgmt API (#108), though.
