### ISSUE TITLE
`nz-number` is defined as a non-zero 32bit unsigned integer, not 64bit.

### ISSUE THREAD

**Issue by jstedfast** [greenmail-mail-test/greenmail#247]
Greenmail returns the following UIDVALIDITY response code:

```
* OK [UIDVALIDITY 1528896777421]
```

Note how that value is 64bit, not 32bit.

Line 4895 of rfc3501 defines `nz-number` as follows:

```
nz-number       = digit-nz *DIGIT
                    ; Non-zero unsigned 32-bit integer
                    ; (0 < n < 4,294,967,296)
```

And it also defines the UIDVALIDITY resp-code as follows:

```
"UIDVALIDITY" SP nz-number
```

**Comment by marcelmay** [comment]
Thx, @jstedfast !

**Comment by jstedfast** [comment]
Always glad to help :)
