### ISSUE TITLE
Preload email files during greenmail start

### ISSUE THREAD

**Issue by mdemori** [greenmail-mail-test/greenmail#250]
Hi, 

I need to use greenmail as standalone server with IMAP settings (this because my application is not written in Java). 
my application work as follow:
- read all email from one IMAP folder, 
- check all message attachment for specific pattern and if the patters has found download the file
- move the  message to another folder as backup,
The problem is that I found some strange cases with attachments that I need to test.

I already download these email as eml from my production server (i can have also as mbox format).

There is a way to "preload" this specific e-mails using an external file immediately after greenmail has started? in this way I can test this cases more quickly than using a real server.

**Comment by benr77** [comment]
Has this functionality been implemented? 

I would like to spin up the Docker image and have an IMAP mailbox already preconfigured with the example emails. There is a mention of this in the docs but no further details that I can see.

Thank you.

**Comment by marcelmay** [comment]
@benr77 : Not yet, but soon.

**Comment by varminas** [comment]
Looking forward for SpringBoot 3 support
