### ISSUE TITLE
Append Message is so slow

### ISSUE THREAD

**Issue by jupan1994** [greenmail-mail-test/greenmail#251]
Hi, I am new here, not sure why my code to append the MimeMessage into MailFolder is so slow? Basically, I first get a list of messages from the Gmail server, then I append these messages into MailFolder , then an email client may fetch them. The method I used is MailFolder.appendMessage(). Any ideas? Thx

**Comment by buildscientist** [comment]
@jupan1994 Do you have any example code to show us what you're doing?

**Comment by marcelmay** [comment]
@jupan1994 , thx for the code snippet.

I ran a profiler on an artifical micro benchmark appending 4k messages and found some improvements (see my commit).

- Can you try with latest master? Do you see an improvement?
- How many emails are we talking about?
- Which version of GreenMail do you use?

Cheers,
Marcel

**Comment by marcelmay** [comment]
Thx for the feedback, @jupan1994 .

That was a quick win so far, and I'm afraid further tuning would require more extensive changes.

Regarding downloading and appending: For thousands of emails I'd try to have one (producer) thread downloading emails, and another (consumer) thread appending the messages.

@buildscientist :  Any further tuning ideas?

I plan to do a 1.5.8 release soon. Unless we find some further improvements, I'd like to close the issue for the release.

**Comment by jupan1994** [comment]
@marcelmay @buildscientist Thank you for your great work! Your comments are more than helpful!

**Comment by buildscientist** [comment]
Agree on the producer/consumer pattern. @jupan1994 what are you trying to accomplish here? Is there any reason you can't just bulk download the emails from Gmail using their REST API and batch feed it into GreenMail?

**Comment by jupan1994** [comment]
@marcelmay @buildscientist 
First, I want to correct my mistake 

> "We are talking about thousands of emails. My previous code (what I attached above) is to download all of them and append them all into Greenmail storage, in this way, Email client has to wait for a long time do send any IMAP commands. Now, I changed to download one email and append one email, so that the Email client can fetch emails while downloading. It's more user-friednly. I don't know if I my logic is correct, I would be grateful if you could share your thoughts."

Please neglect this paragraph ...
Actually, I did do the bulk download and batch feed, sorry for the confusion. I was messed up with something here. 

So, the core of this issue is the performance of **appendMeesage()** method. I guess I already had a answer. Thank you guys!

**Comment by buildscientist** [comment]
@jupan1994 you could create multiple MailFolders and then allocate a thread per MailFolder to append emails to. 

Of course you'd need to figure out a way to split the emails you're getting from Gmail. Perhaps by sender?

**Comment by buildscientist** [comment]
Closing this as @marcelmay provided a fix in 5de9b47 and I provided a potential design solution to @jupan1994
