### ISSUE TITLE
Send and receive emails (for testing clients)

### ISSUE THREAD

**Issue by ralphtheninja** [greenmail-mail-test/greenmail#252]
I'm looking for a simple server for testing sending and retrieving emails in Delta Chat and I'm wondering if `greenmail` can be used for this. My main use case is basically:

* two different users connecting to smtp and imap
* they both send emails using smtp and retrieve using imap

It's perfectly fine if the users (clients) use the same server, so there's no need to send emails from one server to another. Would `greenmail` be a good fit for this testing use case?

**Comment by marcelmay** [comment]
Hi @ralphtheninja , 

that should work (multiple users, smtp and imap).

* Would you run GreenMail as [standalone docker image](http://www.icegreen.com/greenmail/#deploy_docker_standalone), for testing Delta Chat?
* Does Delta Chat require IMAPS/SMTPS for testing? If so, how does Delta Chat deal with self signed/untrusted certificates?
* Delta Chat requires #189, right?

**Comment by ralphtheninja** [comment]
> Would you run GreenMail as standalone docker image, for testing Delta Chat?

Yes, that's the idea. On e.g. Travis.

> Does Delta Chat require IMAPS/SMTPS for testing? If so, how does Delta Chat deal with self signed/untrusted certificates?

Not really. The tests would be running on localhost, so security isn't important for that reason. But on the other hand it would be nice to have. Afaik, there are no warnings when connecting to a server with a self signed certificate.

> Delta Chat requires #189, right?

Correct. The smtp client ([`libetpan`](https://github.com/dinhviethoa/libetpan)) complains if the server isn't implementing `AUTH`.

**Comment by buildscientist** [comment]
> Not really. The tests would be running on localhost, so security isn't important for that reason. But on the other hand it would be nice to have. Afaik, there are no warnings when connecting to a server with a self signed certificate.

That would depend on your SSL library right? 

Note: GreenMail uses an **expired** self-signed certificate so if you're using SMTP/IMAP over TLS your mail client may throw warnings/errors about this. 

FYI - there's an enhancement in #130 to support dynamic loading of SSL certificates.

**Comment by buildscientist** [comment]
> Yes, that's the idea. On e.g. Travis.


You could fetch the GreenMail Docker image from Docker Hub via TravisCI

Alternatively - a better approach would be for you to create a Docker Compose file that includes GreenMail's Docker image and one for Delta-Chat. 

If you do plan on contributing one - see [GreenMail Docker Clients](https://github.com/greenmail-mail-test/greenmail/tree/master/greenmail-docker/clients) for some examples.
