### ISSUE TITLE
Is Gmail client's (phone) behavior related to GreenMail implementation?

### ISSUE THREAD

**Issue by jupan1994** [greenmail-mail-test/greenmail#254]
Hi folks,

I am wondering does GreenMail implementation affect Gamil client's behavior. As a mobile email client, I assume it does not want to download all emails from the server. But when I config Gmail app to connect to GreenMail, it first fetches all email headers. then it fetches all the emails' body one by one. In my imagination, the Gmail client should have some kinds of traffic control instead all fetch all emails in the server mailbox. So I am wondering if the Gmail app's behavior somehow changed by GreenMail?

Thank,
Ju

**Comment by buildscientist** [comment]
@jupan1994 

I can't speak on behalf of how the Gmail mobile client works but I would imagine that it is heavily dependent on the peer it's connecting to. 

GreenMail supports IMAPv4 and the behavior you're describing appears to be correct. 

Were you expecting different behavior?

**Comment by marcelmay** [comment]
As @buildscientist says it really depends on the servers IMAP capabilities (basically there is a negotiation of features when connecting).

There's a [JavaMail GMail FAQ](https://javaee.github.io/javamail/FAQ#gmail) pointing out some GMail IMAP specialities.

**Comment by marcelmay** [comment]
More [JavaMail and GMail specialties](https://javaee.github.io/javamail/Gmail)
