### ISSUE TITLE
add more protocols - e.g. for chat over email

### ISSUE THREAD

**Issue by webermike** [greenmail-mail-test/greenmail#259]
Hello, Marcel and all
Greenmail is a very easy to set up server - even in RAM and also self configuring.
There are clients which provide Chat over Email. This protocol is called POPTASTIC.
Read more about it here: https://compendio.github.io/goldbug-manual/
Next to crypto chat over email, there is the chat server for echo packets, a second protocol.
Several chat clients like spot-on, goldbug, smoke and other use this protocol for chat.

The request here is, to add also support for the echo protocol into greenmail.
And second, to make it more optimized for the POPTASTIC protocol in terms of self configuring.
The java code for an echo server can be found here
https://github.com/textbrowser/smokestack
the idea is that greenmail supports both, chat and email over greenmail, using the POPTASTIC and the ECHO protocol.

If that is given, third, the idea could be to test echo packets over imap. this would require a very fast and stable greenmail server. Or can the echo server even combined with the imap/pop server of greenmail?

if there is interest, please research further. 
Maybe greenmail can be installed on an android device. the server admin provides an IP and Port.
with that a POPTASTIC client auto-configures an IMAP/POP3 account and use the server as long as it exists for chat. or, the echo protocol is used and the greenmail server sends out echo packets to all known clients as the echo packet comes in. For both ways chat over greenmail would be established.
and in case the clients would be able to send echo packets over email, this would be a stress test for greenmail to forward such an email to all known email accounts in greenmail. 

will chat over email be the future of a greenmail server?
The request is to have easy to set up chat servers in your pants.
Regards

**Comment by marcelmay** [comment]
Out of scope of this project.

GreenMail is primarily an email server sandbox(!) for testing.
