### ISSUE TITLE
Cannot SELECT INBOX with greenmail.auth.disabled

### ISSUE THREAD

**Issue by jonhoo** [greenmail-mail-test/greenmail#265]
With `greenmail.auth.disabled`, I can log in as a new user that is created on-the-fly. However, I cannot then perform `SELECT INBOX` (over IMAP): I get "SELECT failed. No such mailbox".

If I send an e-mail *to* this new user, `INBOX` is created, but it'd be great if `INBOX` were created the same time the user is, so that tests like [this one](https://github.com/jonhoo/rust-imap/blob/master/tests/imap_integration.rs#L72-L78) can work.

**Comment by marcelmay** [comment]
@jonhoo  : Can you provide the verbose output? 

I successfully ran your test using GreenMail 1.5.9 and the following modification:
```diff
 #[test]
-#[ignore]
 fn inbox_zero() {
     // https://github.com/greenmail-mail-test/greenmail/issues/265
-    let mut s = session("readonly-test@localhost");
+    let mut s = session("readonly-test-inbox-zero@localhost");
     s.select("INBOX").unwrap();
     let inbox = s.search("ALL").unwrap();
     assert_eq!(inbox.len(), 0);
```

**Comment by jonhoo** [comment]
Huh, looks like this works just fine with 1.5.9, so let's close it! No need to even change the e-mail address!
