### ISSUE TITLE
IMAP Idle support 

### ISSUE THREAD

**Issue by igorgripas** [greenmail-mail-test/greenmail#275]
It seems like greenmail cannot be used while testing application working via imap idle. Is there any way around this issue? Is direct idle support going to be implemented in the nearest future?

**Comment by marcelmay** [comment]
[IMAP IDLE](https://tools.ietf.org/html/rfc2177) would be a nice new feature.

Currently GreenMail does not claim to support IDLE when announcing its CAPABILITIES.

**Comment by michal-kroliczek** [comment]
So I need it as well :) Have anything changed since last comment?

**Comment by apinske** [comment]
I sketched out a simple implementation in #382. What do you think of it? That should be enough to use it with spring-integration.

**Comment by marcelmay** [comment]
Merged #382 . Thx alot, @apinske .
