### ISSUE TITLE
GreenMail cannot receive bounce messages

### ISSUE THREAD

**Issue by buildscientist** [greenmail-mail-test/greenmail#28]
(migrated from http://sourceforge.net/p/greenmail/bugs/6/)

My application reads a POP3 mailbox and resends the messages it reads after processing. When this fails, it needs to generate and send a bounce message. GreenMail cannot receive these bounce messages, as it doesn't recognize <> as MAIL FROM: argument.

Example SMTP session:

```
220 BOLNL-W7453/10.10.132.14 GreenMail SMTP Service Ready
EHLO BOLNL-W7453.local.nl.bol.com
250 BOLNL-W7453/10.10.132.14
MAIL FROM:<>
501 Malformed email address. Use form email@host
```

**Comment by kcberg** [comment]
This problem got shifted down to the RcptCommand class resulting in the error "503 MAIL must come before RCPT"
