### ISSUE TITLE
Quoted charset not accepted on IMAP "SEARCH" command

### ISSUE THREAD

**Issue by greenfoo** [greenmail-mail-test/greenmail#288]
An IMAP SEARCH command might send something like this:
> PMn5AW UID SEARCH CHARSET UTF-8 1:*

...which works ok. But when the argument to CHARSET in surrounded by quotes, GreenMail returns an error:
> PMn5AW UID SEARCH CHARSET "UTF-8" 1:*

According the the IMAP RFC (here: https://tools.ietf.org/html/rfc3501#page-89) this search argument *can* be quoted:
> search          = "SEARCH" [SP "CHARSET" SP astring] 1*(SP search-key)
> astring         = 1*ASTRING-CHAR / string
> string          = quoted / literal
> ...

**Comment by marcelmay** [comment]
Thx, @greenfoo . Release 1.5.11 will be coming soon and include this fix.
