### ISSUE TITLE
MailCommand param pattern too greedy for outlook.com

### ISSUE THREAD

**Issue by shadogray** [greenmail-mail-test/greenmail#291]
outlook.com appends an AUTH field to the MAIL command, which is not handled by the current "PARAM" Pattern:
command=MAIL FROM:<thomas_tester@outlook.de> AUTH=<>
EUR02-AM5-obe.outbound.protection.outlook.com

`Pattern PARAM = Pattern.compile("MAIL FROM:\\s?<(.*)>", ...)`
produces: 
`"thomas_tester@outlook.de> AUTH=<"`

The simple change from greedy to non-greedy: 
`"MAIL FROM:\\s?<(.*?)>.*"`
or exclusion - IMHO preferred, because more precise:
`"MAIL FROM:\\s?<([^>]*)>.*"`
would solve the issue correctly

**Comment by marcelmay** [comment]
Thx alot!

This fixes handling the additional [ESMTP](https://tools.ietf.org/rfc/rfc1869.txt) parameters such as the mentioned AUTH=... .
