### ISSUE TITLE
Is it possible to have a CatchAll account?

### ISSUE THREAD

**Issue by ceisele-r** [greenmail-mail-test/greenmail#295]
Is it possible to configure a user (with an email like catchall@mydomain.com) as CatchAll account so that all emails sent to whatever user (user1@mydomain.com) end up in this mailbox (catchall@mydomain.com)?

**Comment by marcelmay** [comment]
Are you trying to get all emails via IMAP, or programmatically as part of a Unit test?

You can programmatically fetch all messages received via [GreenMail#getReceivedMessages()](http://www.icegreen.com/greenmail/javadocs/com/icegreen/greenmail/base/GreenMailOperations.html#getReceivedMessages--)  :
```java
GreenMail greenMail = ....

MimeMessage[] allMessages = greenMail.getReceivedMessages()
```

**Comment by ceisele-r** [comment]
@marcelmay thanks for the answer. I am trying to get all emails via IMAP, so the programmatic possibility is unfortunately not an option.

**Comment by marcelmay** [comment]
This would require additional, artificial meta folders to avoid UID issues etc

Example:
```
<Catch all User INBOX>
                   |-- <User X>
                   |       |-- INBOX
                   |      ...      |-- Message#1
                   |      ...      |-- Message#2
                   |      ...      |-- SOME FOLDER
                   |      ...     ...       |-- Message#3
                   |      ...     ...      ...
                   |-- <User Y>
                   |       |-- INBOX
                  ...     ...
```

What about these alternatives:
- Can you configure a catch-all user, and CC/BCC him?
- Can you crawl all users and retrieve all messages - is this a unit test scenario?

**Comment by ceisele-r** [comment]
@marcelmay thanks for the response, I see.
Yes, this is an integration test scenario.

I now solved it using one catch-all user that receives all the mails which works for the desired use-case.
Thanks for your support!
