### ISSUE TITLE
Broken links to binaries at http://www.icegreen.com/greenmail/#download

### ISSUE THREAD

**Issue by arazgulyaev** [greenmail-mail-test/greenmail#298]
1. Go to http://www.icegreen.com/greenmail/#download
2. Try to click any link representing an artifact

OBSERVED: Server responses with "501 HTTPS Required".
EXPECTED: Artifact can be downloaded

**Comment by marcelmay** [comment]
Thx alot, @arazgulyaev 

The links changed and require https instead of http.

**Comment by marcelmay** [comment]
Just deployed site, closing now.
