### ISSUE TITLE
Support for Delivery Status Notification

### ISSUE THREAD

**Issue by wolftobias** [greenmail-mail-test/greenmail#307]
We have the need to test the support of DSN and we like to use GreenMail as a sparing partner.

```
--> sender
RCPT <email-address> NOTIFY=SUCCESS

GreenMail Server
<-- send DSN email back
Reporting-MTA: dns; localhost.
Arrival-Date: Fri, 28 Feb 2020 14:13:54 XXXXX (CET)

Final-Recipient: rfc822; user1@test
Action: delivered
Status: 2.0.0
```

**Comment by apinske** [comment]
I am interested in this as well. I did a really rough draft in https://github.com/greenmail-mail-test/greenmail/pull/387 just to start a discussion about the details:

- what kind of notifications do we need (status/notification)
- what formats do we want to support
    - some mail servers create DSN as in the RFC
    - some just send human-readable messages
    - informal survey of some servers (4 out of 12 send RFC-conforming)
- how will we configure the when and the what
- ...
