### ISSUE TITLE
Add Greenmail-HTTP to the documentation

### ISSUE THREAD

**Issue by davidnewcomb** [greenmail-mail-test/greenmail#314]
@marcelmay You offered to add my project to your documentation. I'm about ready for a version 1.
As it turned out, it really helped me identify and fix several issues with GreenMail and I think it will be a good compliment to the testing suite. It remove the need to set up mail clients or write software to get the mail out of Greenmail.

https://github.com/davidnewcomb/greenmail-http

**Comment by marcelmay** [comment]
@davidnewcomb , I added the project to the links section:

https://greenmail-mail-test.github.io/greenmail/#links

**Comment by davidnewcomb** [comment]
Many thanks
