### ISSUE TITLE
Official website and documentation

### ISSUE THREAD

**Issue by davidnewcomb** [greenmail-mail-test/greenmail#315]
There are 2 sets of documentation for GreenMail

http://www.icegreen.com/greenmail/
https://greenmail-mail-test.github.io/greenmail/

Both sites say they refer to Greenmail 1.5.13 but each page is different. Different Nav bar most noticeably but also missing/old content on the icegreen site.

Expected behaviour:
Update office site with new docs or forward visited to the new site.
I noticed it because the fix for #314 is not in the official documentation.

It's not good enough to say our official documentation lives at GitHub and people should look there for 2 reasons:
1. Type GreenMail into Google and you get the icegreen version first, not the "official" version.
1. There's no clear message to say you are looking at out of date documentation and a link to the new documentation.

**Comment by marcelmay** [comment]
Thx again, @davidnewcomb !

**Comment by davidnewcomb** [comment]
I was thinking, if they are 2 separate web spaces you could save yourself a bit of update time by changing the DNS of your Pages site.

https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by marcelmay** [comment]
I added a permanent redirect. I did not know about the DNS, thx!
