### ISSUE TITLE
Add support for jakarta.mail 2.0

### ISSUE THREAD

**Issue by uberskigeek** [greenmail-mail-test/greenmail#317]
- Maven dependencies
- Javadoc links (pom.xml)
- Check [release note](https://eclipse-ee4j.github.io/mail/) for further actions
Jakarta 2.0 has renamed the javax.mail packages to jakarta.mail along with some enhancements.

**Comment by marcelmay** [comment]
Thx, @uberskigeek .

Pulled the PR into branch  [issue-317-jakarta-mail-2-0](/greenmail-mail-test/greenmail/tree/issue-317-jakarta-mail-2-0).

**Comment by oliverlietz** [comment]
Can we have an early 2.0 release with `jakarta.mail`, please?

**Comment by Airblader** [comment]
@marcelmay First off, thanks for this great project! I'd really love to use GreenMail for automated tests, but this would force me to downgrade, which I'd like to avoid.

Would you mind elaborating what the current situation / issues are since a branch does seem to exist? Can we help somehow?

**Comment by marcelmay** [comment]
@Airblader , I'll try to tackle that over upcoming easter vacation.

I try to keep GreenMail and JakartaMail major/minor versions in sync, and for a GreenMail 2.0 I'd like to use the chance to cleanup and deprecate some features. But an 2.0 pre release candidate for easter should work out.

**Comment by Airblader** [comment]
That makes sense. Thanks for the response, looking forward to it!

**Comment by marcelmay** [comment]
I created a new [release 2.x preview branch](/greenmail-mail-test/greenmail/tree/release_2_0_preview), which contains the pulled in Jakarta Mail 2.0 changes rebased on latest master.

**Comment by RaphaelJenni** [comment]
@marcelmay Thanks a lot for the project and for keeping it alive!

Regarding the 2.x version with the jakarta.mail 2.0 support. Is it possible for you to release a beta/preview version to maven? This way we wouldn't have to build it manually and include it as a jar into our project.

**Comment by marcelmay** [comment]
@RaphaelJenni , just released an [2.0.0-alpha-1](https://repo.maven.apache.org/maven2/com/icegreen/greenmail/2.0.0-alpha-1/) for you. Any feedback appreciated.

**Comment by marcelmay** [comment]
@uberskigeek , thx alot for this PR. Sorry it took some time, now it is the base for GreenMail 2.0

**Comment by michaelhixson** [comment]
2.0.0-alpha-1 looks good in my app's tests.  Thanks.

**Comment by RaphaelJenni** [comment]
@marcelmay  thanks a lot for the alpha release. So far all tests are running as expected. 

Only thing I had to add was the `implementation("jakarta.activation:jakarta.activation-api:2.0.1")` dependency for solving the `NoClassDefFoundError: jakarta/activation/DataSource` ([Maven Repo](https://mvnrepository.com/artifact/jakarta.activation/jakarta.activation-api/2.0.1)) error.

**Comment by marcelmay** [comment]
@RaphaelJenni , thx for the feedback. This will be fixed by #385 .

The jakarta.activation-api should be added, as also GreenMailUtil imports API classes.

It seems com.sun.mail:jakarta.mail transitively pulls in com.sun.activation:jakarta.activation, which contains both activation and activation-api ... so a NCDFE should not happen. Anyway, dependency will be added.
