### ISSUE TITLE
message body encoding issue

### ISSUE THREAD

**Issue by waelchatila** [greenmail-mail-test/greenmail#32]
just got an email from a user:

-
One minor issue I would like to mention in case you are not yet aware of it. The message body in multipart messages does not properly work with encodings other than us-ascii. I see 'us-ascii' hardcoded at various locations. First I tried rewriting getWholeMessage, but it did not solve my issue with utf8 chars. I presume this is not the only point where the encoding gets broken.

   public static String getWholeMessage(Part msg) {
        try {
            ByteArrayOutputStream bodyOut = new ByteArrayOutputStream();
            msg.writeTo(bodyOut);
            return bodyOut.toString("US-ASCII").trim();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

Regards

Marc

**Comment by rania-globalorange** [comment]
Hi, 
What is the current status about this? Will it be in version 1.5 and if so when can we expect it?

Thanks a lot!

**Comment by marcelmay** [comment]
Hi @rania-globalorange ,

we plan a 1.5 for around new year.

If you want to help, you could provide a test case (or even a patch)... thx!

**Comment by marcelmay** [comment]
Hi @rania-globalorange ,
I integrated some fixes based on the Alfresco patch. It's deployed as latest SNAPSHOT.
Can you give it a try if it is still an issue? I tried to provoke it with different file.encoding settings etc.

Thx!

**Comment by marcelmay** [comment]
Closing issue. Please reopen if persists.
