### ISSUE TITLE
Support mail.mime.allowutf8

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#320]
See previous [discussion](https://github.com/greenmail-mail-test/greenmail/issues/257#issuecomment-618478321).

- Requires JavaMail 1.6

**Comment by Uni2K** [comment]
So whats the status? It seems like the encoding is still not working 1.6.2.
![grafik](https://user-images.githubusercontent.com/20185223/108415148-6d6eba00-722d-11eb-8ed2-eac3745d3cfa.png)
