### ISSUE TITLE
Support Subaddressing

### ISSUE THREAD

**Issue by blockerdude** [greenmail-mail-test/greenmail#337]
A common feature of many full fledged email clients is [subAddressing](https://en.wikipedia.org/wiki/Email_address#Subaddressing)

Which to the best of my knowledge is not supported by greenmail.

This feature would be incredibly useful for people using the standalone server and who have many emails. At the moment each user/password combo needs to be added as an environment variable `-Dgreenmail.users` as described [here](https://greenmail-mail-test.github.io/greenmail/#deploy_standalone)

The current behavior for a user sending to the smtp server that is not currently recognized is to create a user and provide it with a password that is equal to its email.
 `INFO           smtp.SmtpManager| Created user login dummy+extension@example.com for address dummy+extension@example.com with password dummy+extension@example.com because it didn't exist before.`

So for an environment with many emails a large number of users must be manually created if it is desired to access these accounts using IMAP under the assumption of subAddressing. 

Alternatively if there is a work around I would happily use that instead. 

Some version information

Greenmail standalone docker version: ```greenmail/standalone:1.5.14``` 

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by marcelmay** [comment]
So as a workaround until GreenMail supports [rfc5233 sub adressing](https://tools.ietf.org/html/rfc5233), the localpart detail should be ignored?

Example:
Mail to `dummy+extension@example.com` would be delivered to `dummy@example.com` (ignoring `extension` detail ).
So you would only need to create a single GreenMail user, and at least the emails would be delivered to the right user.

There's been a previous discussion regarding Sieve : #41

This feature should also be activated by a GreenMail configuration flag (eg `-Dgreenmail.sieve.ignore.detail`)

**Comment by blockerdude** [comment]
@marcelmay I didn't know there was a RFC for it, or that it was called sieve filtering/another discussion had already taken place. 

To your suggestion about a config flag is fantastic though, I think that is exactly what is needed. An optional flag that allows users to opt in to the functionality they want.

**Comment by Jaap-Jan** [comment]
I've made a pull request which adds subaddress handling. Essentially, it strips the subaddress before delivery, as if the sender used the address without a subaddress. Maybe this is a bit too rough because the log also doesn't mention the subaddress at all, but it works.

I would like to get this merged, so please let me know what you think.
