### ISSUE TITLE
Call hook after starting GreenMail in GreenMailRule

### ISSUE THREAD

**Issue by NiceWeather** [greenmail-mail-test/greenmail#338]
We are using GreenMail for our tests.  After setting up GreenMail with a dynamic port, we have to configure our application to send mails to the dynamically configured port at localhost.  We think that there are many other projects with similar problems.

We used GreenMailRule with the annotation @ClassRule.  And in a @BeforeClass-method we configured our application.  We had to do this in several test classes.  Now, we decided to write our own rule (planned as a subclass of GreenMailRule) to make all these things.  We wrote this rule by copy-and-pasting GreenMailRule because there is no possibility to insert commands after starting GreenMail and before continuing to the test.  (Of course, we could use a rule chain, but the code looks worse.)

We want to propose the creation of an empty method "doAfterStart" in GreenMailRule.  This method should be called directly after "start()" and before "base.evaluate()":
```
        try {
          start();
          doAfterStart();
          base.evaluate();
        } finally {
          stop();
        }
```

We use version 1.5.13.  But the code in the master branch looks identical.

**Comment by marcelmay** [comment]
Would overriding `start()` work as well for your case?

```java
    @Rule
    public final GreenMailRule greenMail = new GreenMailRule(ServerSetupTest.ALL){
        @Override
        public void start() {
            super.start();
            // Do something after start
        }
    };
```

**Comment by NiceWeather** [comment]
Yes, this works great, of course.  Thanks for this obvious hint.
