### ISSUE TITLE
Could not use full email address as login name in standalone version

### ISSUE THREAD

**Issue by ingowalther** [greenmail-mail-test/greenmail#345]
Hello,

I need to use a full email address as login name in the standalone version.
Currently this is not possible because in https://github.com/greenmail-mail-test/greenmail/blob/1b12e338da70599e99f80f80516f6513127a7a86/greenmail-core/src/main/java/com/icegreen/greenmail/configuration/PropertiesBasedGreenMailConfigurationBuilder.java#L60 always the username will be used as login.

Would it be possible to introduce another parameter to use the complete email address as login name?

**Comment by marcelmay** [comment]
Hi @ingowalther,

thx for the feedback.

Such option is indeed missing, so there will be a flag ```-Dgreenmail.users.login=email``` to override the behavior.

**Comment by ingowalther** [comment]
Hello @marcelmay,

thank you for this fast implemtation! Great work!
