### ISSUE TITLE
Add support for starting up with a automatically selected available port

### ISSUE THREAD

**Issue by sparsick** [greenmail-mail-test/greenmail#349]
Like Wiremock, Mockserver and Testcontainer are doing it, it would be awesome, if Greenmail could find a free port on the machine by itself. The benefit is that the developer needn't care if the needed port for Greenmail is free on the machine that running the tests.

Furthermore, the developer should have a possibility to ask Greenmail which port is selected. 

Current workaround: 

```java
    private static int smtpPort = SocketUtils.findAvailableTcpPort();
    private static final ServerSetup SERVER_SETUP_SMTP = new ServerSetup(smtpPort, null, ServerSetup.PROTOCOL_SMTP);
```

**Comment by marcelmay** [comment]
If you set the port to 0, GreenMail will actually try to find an available port (see [example](https://github.com/greenmail-mail-test/greenmail/blob/2e5eb9f203317c7b31a951ce5b22c1943b426159/greenmail-core/src/test/java/com/icegreen/greenmail/server/AllocateAvailablePortTest.java)).

The documentation definitely needs an update describing this feature, and a convenience method for creating a `ServerSetup` configuration, eg `ServerSetup.PROTOCOL_SMTP. dynamicPort()` , similar as you suggested with WireMock. Thx alot!

**Comment by marcelmay** [comment]
Updated [example link](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/server/AllocateAvailablePortTest.java) with `dynamicPort()`

**Comment by sparsick** [comment]
Thank you for pointing me to the example and updating the documentation. I didn't find it.
