### ISSUE TITLE
Purge mailbox/(es) in docker container

### ISSUE THREAD

**Issue by gera-wolkow** [greenmail-mail-test/greenmail#356]
Impossible to purge mailbox in docker container using connection like:
`    public void clearMail () throws FolderException {
   final ServerSetup serverSetupIMAP = new ServerSetup(environmentConfig.getMailMockPort(), environmentConfig.getMailMockHost(), ServerSetup.PROTOCOL_IMAP);
    final GreenMail greenMail = new GreenMail(serverSetupIMAP);
      greenMail.purgeEmailFromAllMailboxes();
   }`

Please help. Am I doing something wrong or there is no ability to do it for docker?

**Comment by marcelmay** [comment]
@gera-wolkow, you have to either use [IMAP to remotely purge the mailboxes](https://stackoverflow.com/questions/3180891/imap-how-to-delete-messages) for all accounts, or restart the container.

There's a plan to extend the [GreenMail Webapp deployment](https://greenmail-mail-test.github.io/greenmail/#deploy_webapp) for such a purge API call.

**Comment by marcelmay** [comment]
GreenMail 1.6.2 standalone (and therefore GreenMail docker) will have a reset and purge feature via a newly [exposed API](https://greenmail-mail-test.github.io/greenmail/#features).

**Comment by marcelmay** [comment]
You can now purge all mails via `http://localhost:8080/api/mail/purge` in GreenMail 1.6.2 standalone.
