### ISSUE TITLE
FIPS complaint version

### ISSUE THREAD

**Issue by sunkarv** [greenmail-mail-test/greenmail#369]
Hi,

Do you have a FIPS-compliant version of greenmail? if not what is the alternative version we should use?

<img width="809" alt="Screenshot 2021-02-08 at 12 26 33 PM" src="https://user-images.githubusercontent.com/4946411/107324938-e6a03b80-6ace-11eb-8fe9-33a49fb5424c.png">

the above-mentioned ciphers are not FIPS complaint and were hard coded in your code.

Thanks,
Ravindra

**Comment by marcelmay** [comment]
Hi @sunkarv,

thx for pointing this out but please read the docs in the class [DummySSLServerSocketFactory](https://github.com/greenmail-mail-test/greenmail/blob/a05f6aee0fc5b4d19e079144ef41ab48e2ce4f6a/greenmail-core/src/main/java/com/icegreen/greenmail/util/DummySSLServerSocketFactory.java) containing that fragment.

The DummySSLServerSocketFactory states explicitly that it is not secure, and how to use your own certificates.

Please be aware that GreenMail is a testing/mocking framework and is not intended to be deployed in production environments. What is your use case for GreenMail FIPS compliance, can you elaborate?
