### ISSUE TITLE
AUTH LOGIN wrong request codes

### ISSUE THREAD

**Issue by Uni2K** [greenmail-mail-test/greenmail#370]
If you try the current AuthCommand (SMTP) with Outlook and AUTH LOGIN, you will notice that it won't work.
The reason is that in the file:
https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/smtp/commands/AuthCommand.java

Line 99 and 101 contain the wrong request code.
It should be the ones stated here:
https://www.samlogic.net/articles/smtp-commands-reference-auth.htm

If you replace them, Outlook will work fine.

**Comment by marcelmay** [comment]
Thx alot, @Uni2K
