### ISSUE TITLE
UTF-8 Encoding still not working 

### ISSUE THREAD

**Issue by Uni2K** [greenmail-mail-test/greenmail#371]
In version 1.6.2 the encoding is still not working, see the screenshot.
From the previous issue 
https://github.com/greenmail-mail-test/greenmail/issues/32
it is unclear how to resolve this.

![grafik](https://user-images.githubusercontent.com/20185223/108415310-aad34780-722d-11eb-8855-652741181004.png)

The screenshot is showing the content of the MovingMessage inside the DataCommand.java right after the DATA command was issued.

**Comment by marcelmay** [comment]
@Uni2K ,

can you provide a test case? GreenMai verbose output or an exported test email (.eml) would help, too.

There is a test case in [ImapServerTest#testRetreiveSimple()](https://github.com/greenmail-mail-test/greenmail/blob/17278ff65a873b19c5460a389a73e8f61769be99/greenmail-core/src/test/java/com/icegreen/greenmail/test/ImapServerTest.java#L48) encoding including umlauts.

**Comment by Uni2K** [comment]
@marcelmay 
Found the reason:
In the file: https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/smtp/SmtpConnection.java

you are still using US_ASCII. Replace it with UTF-8 (maybe also check the other files). I also replaced all ISO encodings with UTF-8 and now everything works ;)

**Comment by marcelmay** [comment]
Thx, @Uni2K . I will try to fix the reading of the encoded message by creating the mime message directly from the input stream (until CRLF-DOT-CRLF reached). That clears some nebulous encoding done here and avoid it by delegating to MimeMessage.

**Comment by marcelmay** [comment]
@Uni2K , I plan to roll out a release this weekend.
