### ISSUE TITLE
Parsing of UID Search command is broken 

### ISSUE THREAD

**Issue by dparamoshkin** [greenmail-mail-test/greenmail#372]
Greenmail 1.6.0 - 1.6.2 fails to parse commands like `UID SEARCH UID 1:*`

`2021-02-24T18:11:51.092Z [imap:127.0.0.1:43157<-/127.0.0.1:38074] WARN  c.i.g.imap.commands.UidCommand:68 - Error processing command: Invalid character: '*' Command should be '<tag> UID <fetch-command>|<store-command>|<copy-command>|<search-command>|<expunge-command>'
com.icegreen.greenmail.imap.ProtocolException: Invalid character: '*'`

Worked before in 1.5.10

**Comment by marcelmay** [comment]
Thanks lot, @dparamoshkin
