### ISSUE TITLE
Documentation - Specify default configs for docker image

### ISSUE THREAD

**Issue by pfournier1** [greenmail-mail-test/greenmail#393]
In the documentation (https://greenmail-mail-test.github.io/greenmail/) it should be mentioned that the docker image sets the default user to "greenmail". It should also mention that the these environment variables are set by default in the docker image "GREENMAIL_OPTS=-Dgreenmail.setup.test.all     -Dgreenmail.hostname=0.0.0.0     -Dgreenmail.auth.disabled"

**Comment by marcelmay** [comment]
Thx alot!
