### ISSUE TITLE
Imap bug with deleting of inbox and renaming folder to existing name

### ISSUE THREAD

**Issue by filtsin** [greenmail-mail-test/greenmail#399]
1. I have a question about the command "DELETE" with the argument "INBOX". As described in RFC3501 "It is an error to attempt to delete INBOX". However, greenmail allows this operation and removes INBOX permanently.

```
c: a02 LIST "" *
s: * LIST () "." "INBOX"
s: a02 OK LIST completed.
c: a03 DELETE inbox
s: a03 OK DELETE completed.
c: a04 LIST "" *
s: a04 OK LIST completed.
```

I think it is strange that we can delete INBOX. 

2. As described in RFC3501 "It is an error to attempt to rename from a mailbox name that does not exist or to a mailbox name that **already exists**."

Example with "INBOX" but it works in the same way with other names.

```
c: a02 LIST "" *
s: * LIST () "." "INBOX"
s: a02 OK LIST completed.
c: a03 CREATE zoo
s: a03 OK CREATE completed.
c: a04 RENAME zoo inbox
s: a04 OK RENAME completed.
c: a05 LIST "" *
s: * LIST () "." "INBOX"
s: * LIST () "." "INBOX"
s: a05 OK LIST completed.
```

It is definitely the bug that we have multiple folders with the same name.

I think I can fix it by myself if you want.

**Comment by apinske** [comment]
@filtsin Thanks for analysing this. You are very welcome to provide a PR for a fix. We'd appreciate it!
