### ISSUE TITLE
Remove JUnit dependency for greenmail-core

### ISSUE THREAD

**Issue by shollander** [greenmail-mail-test/greenmail#420]
Please remove the JUnit dependency from `greenmail-core`.

For those who use use JUnit 5, the unnecessary inclusion of JUnit 4 causes classpath pollution which can cause confusion and errors if the wrong annotations are used.

There are probably also those who don't use JUnit at all and don't want the classpath pollution.

It looks like you have specific artifacts for JUnit 4 and JUnit 5. That is the only place where JUnit dependencies should appear.

Thank you.

**Comment by marcelmay** [comment]
That's the mid term plan, but historically GreenMail has direct dependency on JUnits rule engine.
Work has already started with greenmail-junit4 and greenmail-junit5 modules.

Though not elegant, you should be able to exclude junit4 dependencies when using current GreenMaill.
