### ISSUE TITLE
Support IMAP MOVE command

### ISSUE THREAD

**Issue by micw** [greenmail-mail-test/greenmail#422]
When I try to move mails between folders in imap (using ImapFolder.move()), I always get "MOVE not supported". It would be great if GreenMail would support this.

Edit: the error message comes from JavaMail since "MOVE" is not in the list of the received capabilities".

**Comment by micw** [comment]
Great news, thank you. Do you have a rough timeline for it, so that I can track this and enable my Testcase when it's there? Or is there a releated 2.x issue that I can track?

**Comment by marcelmay** [comment]
I plan to roll a 2.0.0-alpha-3 and 1.6.6 release this weekend.

**Comment by marcelmay** [comment]
Update: Plan to roll release this Wednesday
