### ISSUE TITLE
Fix thread synchronization issues

### ISSUE THREAD

**Issue by camann9** [greenmail-mail-test/greenmail#43]
There are various issues in thread synchronization that are uncovered by the MultiRequestTest (execute multiple times and look at command line output). Those should be fixed. While doing this it might be useful to do a general refactoring of the protocol code.

**Comment by marcelmay** [comment]
Sonar reports 2 blocker issues "Methods "wait(...)", "notify()" and "notifyAll()" should never be called on Thread instances" for AbstractServer and Service. These issues should also be included.
