### ISSUE TITLE
MOVE command does not return CopyUID causing NullPointerException in jakarta.mail

### ISSUE THREAD

**Issue by kumotaicho** [greenmail-mail-test/greenmail#445]
**jakarta.mail** (**1.6.7**) throws `NullPointerException` when using `IMAPFolder.moveUIDMessages` because the **MOVE** command does not return the **CopyUID** (**greenmail 1.6.6**).

**Comment by marcelmay** [comment]
GreenMail expected a UID MOVE command, but JavaMail actually only sends a MOVE without UID:

```
A10 MOVE 1:3 INBOX.target-folder
* 1 EXPUNGE
* 1 EXPUNGE
* 1 EXPUNGE
A10 OK MOVE completed.
```

According to the [MOVE RFC](https://datatracker.ietf.org/doc/html/rfc6851#section-3.2), it should have been a `UID MOVE` like this:
```
C: a UID MOVE 42:69 foo
S: * OK [COPYUID 432432 42:69 1202:1229]
S: * 22 EXPUNGE
S: (more expunges)
S: a OK Done
```
It seems to be a known issue with JavaMail: https://github.com/eclipse-ee4j/mail/issues/329

For now GreenMail will change to always return the COPYUID.

**Comment by marcelmay** [comment]
Thx alot for raising this issue @kumotaicho , there will be a small 1.6.7 release soon.

**Comment by kumotaicho** [comment]
Thank you very much for your quick reply and reaction @marcelmay !
