### ISSUE TITLE
Rewrite Greenmail website

### ISSUE THREAD

**Issue by camann9** [greenmail-mail-test/greenmail#45]
The website is being rewritten based on Bootstrap. First prototype ready.

**Comment by marcelmay** [comment]
Merged pull request (see #54 ) overwriting original site with new bootstrap based site.

Technical, the redesigned site is based on:
- Bootstrap 3.3.1
- Colors from http://www.google.com/design/spec/style/color.html#color-color-palette using “Teal” palette
- Syntax highlighting via prism.js from http://prismjs.com/

**Comment by buildscientist** [comment]
Closing this as the new site is live!
