### ISSUE TITLE
Provide docker image for M1 macbooks (arm64v8)

### ISSUE THREAD

**Issue by wolfey** [greenmail-mail-test/greenmail#455]
Currently, greenmail docker image is only available for amd64. Please support images for arm64 as well.

**Comment by wolfey** [comment]
Should be fairly simple using these instructions: https://github.com/docker/buildx#installing

**Comment by wolfey** [comment]
```
export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx create --name greenmail
docker buildx use greenmail
docker buildx build \
--platform linux/arm64,linux/amd64 \
--tag "greenmail/standalone" \
--push \
.
```

**Comment by ericparton** [comment]
The greenmail docker image crashes immediately on M1 macs; it can't even be run with the integrated QEMU emulation

**Comment by marcelmay** [comment]
Latest release [1.6.9](https://hub.docker.com/layers/standalone/greenmail/standalone/1.6.9/images/sha256-984f68b8b30cb100999cfbb99972a9f9988e89f512ab6c4d07a1213be373f25c?context=explore) now supports linux/amd64 and linux/arm64
