### ISSUE TITLE
Look at various Greenmail forks

### ISSUE THREAD

**Issue by camann9** [greenmail-mail-test/greenmail#46]
There are various forks of greenmail on Github. We should look at the improvements they contain and merge them into our repo (after asking :-P).

**Comment by markrogersalfresco** [comment]
Yes, its great that Greenmail is alive again.    We at alfresco have been patching version 1.3 for a while now.     I'll compare with the latest version and contribute our changes back.    In the meantime the diffs are available from our SVN repo.

**Comment by camann9** [comment]
It would be awesome to have your commits too :-) . please use separate pull
requests for separate contributions where possible.

**Comment by marcelmay** [comment]
There is even an Alfresco specific issue, where we tried to roughly analyze which parts we could reintegrate:
https://github.com/greenmail-mail-test/greenmail/issues/37 <https://github.com/greenmail-mail-test/greenmail/issues/37>

Mark, let me know if/how we can share the work on this.

Cheers,
Marcel

**Comment by buildscientist** [comment]
Closing. We have a number of patches from an Alfresco patch. See #37 for more details.
