### ISSUE TITLE
Problems with unicode in sent message

### ISSUE THREAD

**Issue by StefanLiebig** [greenmail-mail-test/greenmail#460]
Using GreenMail 1.6.9

With the test code from https://greenmail-mail-test.github.io/greenmail/#examples (Testing your sending code (simple)) slightly modified with unicode character and umlaute (Kotlin):

    val greenMail = GreenMail() //uses test ports by default
    greenMail.start()
    GreenMailUtil.sendTextEmailTest(
        "to@localhost", "from@localhost", "some subject",
        "This is a test with ünicöde: \uD83C\uDF36"
    ) // --- Place your sending code here

    assertEquals("This is a test with ünicöde: \uD83C\uDF36", GreenMailUtil.getBody(greenMail.receivedMessages[0]))
    greenMail.stop()

The assertion fails.
Expected is: "This is a test with ünicöde: 🌶"
but is: "This is a test with =C3=BCnic=C3=B6de: =F0=9F=8C=B6"

Is this supposed to work?

**Comment by marcelmay** [comment]
Hi @StefanLiebig ,

you should use msg.content, as `GreenMailUtil.getBody` would fetch the body part structure as text:

```kotlin
@file:DependsOn("com.icegreen:greenmail:1.6.9")
@file:DependsOn("org.jetbrains.kotlin:kotlin-test:1.7.0")

import com.icegreen.greenmail.util.GreenMail
import com.icegreen.greenmail.util.GreenMailUtil
import kotlin.script.experimental.dependencies.DependsOn
import kotlin.test.DefaultAsserter.assertEquals

val greenMail = GreenMail()
greenMail.start()

val content = "This is a test with ünicöde: \uD83C\uDF36"
val subject = "Some sübject"

GreenMailUtil.sendTextEmailTest(
    "to@localhost", "from@localhost", subject,
    content
)

val msg = greenMail.receivedMessages[0]
assertEquals("Checking subject",subject, msg.subject)
assertEquals("Checking content type", "text/plain; charset=UTF-8", msg.contentType)
assertEquals("Checking content", content,  msg.content) // Fetch content
greenMail.stop()
```
This should work, but there seems to be a bug with the content (strange eol?):
```kotlin
java.lang.AssertionError: Checking content. Expected <This is a test with ünicöde: 🌶>, actual <This is a test with ünicöde: 🌶
>.
```

**Comment by StefanLiebig** [comment]
Hi @marcelmay ,

Yes, the actual msg.content contains additional "\r\n".

The tests "Testing your sending code (advanced)" do trim() the content!

**Comment by marcelmay** [comment]
The trailing "\r\n" seems to be a bug in GreenMail SMTP.

This now works for retrieving using IMAP and msg.content.

Unfortunately, this fails for POP3, where JavaMail at the end of a message - CONTENT+'\r\n.\r\n' - only strips '.\r\n'  - so there is always a CONTENT+'\r\n': 
[ com.sun.mail.pop3.Protocol#retr:L523:](https://github.com/javaee/javamail/blob/master/mail/src/main/java/com/sun/mail/pop3/Protocol.java#L523) -> [#readMultilineResponse](https://github.com/javaee/javamail/blob/master/mail/src/main/java/com/sun/mail/pop3/Protocol.java#L822) :

It would be nice if JavaMail msg.content would behave transparent to IMAP or POP3 being used...
