### ISSUE TITLE
"Address already in use: bind" when running on Windows

### ISSUE THREAD

**Issue by markvr** [greenmail-mail-test/greenmail#464]
Running running on Windows, the default configuration fails with `"Address already in use: bind`
My exact windows version is: 10 21H2

Example code:

      GreenMail gm = new GreenMail(ServerSetupTest.SMTP);
      gm.start();

It turns out this is because Windows "reserves" some port ranges, and doesn't allow binding to them. 

This range includes the default ports GreenMail attempts to use:

    netsh interface ipv4 show excludedportrange protocol=tcp
  
    Start Port    End Port
    ----------    --------
          1201        1300
          1301        1400
          2797        2896
          2897        2996
          3023        3122
          3123        3222
          5357        5357
          8181        8280
          8381        8480
          8581        8680
         29196       29295
         29296       29395
         49679       49778
         49779       49878
         49879       49978
         50000       50059

A workaround is:

      GreenMail gm = new GreenMail(ServerSetupTest.SMTP.dynamicPort());
      var port = gm.getSmtp().getPort();

Thanks Windows 🙄 it took me ages to find this out.

Maybe this could be explained in the Greenmail docs or something?

**Comment by marcelmay** [comment]
Thanks, @markvr ! 

Added example and also linked to this issue:
https://greenmail-mail-test.github.io/greenmail/#ex_send_dynamic_port
