### ISSUE TITLE
POP3 response not properly byte-stuffed

### ISSUE THREAD

**Issue by Spunc** [greenmail-mail-test/greenmail#475]
## Problem

When retrieving an e-mail via POP3 that has a termination octet within its content, the response from Greenmail is not byte-stuffed. As a consequence, proper working email clients may cut of the part of the email that follows after that point.

## Affected version

I found the problem with Greenmail/standalone 1.6.9.

## How to reproduce

1. Send an email to Greenmail which contains a termination octet within its content, e. g.
```text
This line will be transferred.

.

This line will not be transferred.
```
2. Connect an email client (I used Thunderbird) via POP3 to the inbox at Greenmail. The client will only download the email until it sees the termination octet.

## Background

[RFC 1939](https://www.ietf.org/rfc/rfc1939.txt) mentions at section 3:
>If any line of the multi-line response
> begins with the termination octet, the line is "byte-stuffed" by
>  pre-pending the termination octet to that line of the response.
>  Hence a multi-line response is terminated with the five octets
>   "CRLF.CRLF".

**Comment by marcelmay** [comment]
Thanks alot, @Spunc ! 

Just backported the fix to [1.6.x](https://github.com/greenmail-mail-test/greenmail/tree/releases/1.6.x) branch if you want to try out snapshot version. I plan to roll a 1.6.11 release this weekend.
