### ISSUE TITLE
Issue with encoding of `from` and `to` fields

### ISSUE THREAD

**Issue by boris-petrov** [greenmail-mail-test/greenmail#478]
Hi, I'm sending an email by doing something like:

```groovy
def message = new MimeMessage(session)
// this intermediate `InternetAddress` is needed because of:
// https://stackoverflow.com/questions/31859901/java-mail-sender-address-gets-non-ascii-chars-removed/31865820#31865820
def address = new InternetAddress('"кирилица" <other@example.com>')
message.from = new InternetAddress(address.address, address.personal)
message.subject = 'some subject with кирилица'
message.content = ...
GreenMailUtil.sendMimeMessage(message)
```

(note the Cyrillic in the `from` address). In the debug logs I see:

```
10:10:43.065 [smtp:127.0.0.1:3025<-/127.0.0.1:33824] DEBUG c.i.greenmail.util.LineLoggingBuffer - C: From: =
?UTF-8?B?0LrQuNGA0LjQu9C40YbQsA==?= <other@example.com>\r\n
```

Which is what I would expect - i.e. the `from` header is correctly encoded and sent over the wire. A few lines down in the logs (where I've received the message):

```
10:10:43.155 [imap:127.0.0.1:3143<-/127.0.0.1:56364] DEBUG c.i.greenmail.util.LineLoggingBuffer - S: 8?Q?som
e_subject_?= =?UTF-8?Q?with_=D0=BA=D0=B8=D1=80=D0=B8=D0=BB=D0=B8=D1=86=D0=B0?=" (("????????" NIL "other" "exampl
e.com")) ([WRAP]
```

The first part is the subject which is correctly received. After that you see the `from` part which has question marks inside. After that, doing a `message.getFrom()[0]` on the received message returns these question marks. What is also strange is that `message.getHeader("From")[0]` returns the correct encoded value - not sure how that happens. But in any case, `getFrom` doesn't work which is not nice.

Am I doing something wrong or is this an issue in `Greenmail`? I spent a lot of time debugging this. :smile:

**Comment by marcelmay** [comment]
Hi @boris-petrov ,

can you provide a test case snippet, e.g. based on [EncodingTest.java](https://github.com/greenmail-mail-test/greenmail/blob/463774bb642b54589e9c1df23b8325ab9697b4a7/greenmail-core/src/test/java/com/icegreen/greenmail/test/specificmessages/EncodingTest.java#L114)?

Which GreenMail version are you using - latest 1.6.10?

**Comment by marcelmay** [comment]
Thx for the test case, that really helped.

`greenMail. getReceivedMessages' fetches the messages directly, without IMAP.
