### ISSUE TITLE
SpringBoot 3.0 and GreenMail 2.0

### ISSUE THREAD

**Issue by tafli** [greenmail-mail-test/greenmail#502]
As of Release 3 of SpringBoot the javax.mail is renamed to jakarte.mail as fixed in #317. Alpha-2 of GreenMail v2 does work/compile so far an I'd like to ask, if there is an ETA on release v2?

**Comment by marcelmay** [comment]
@tafli , I will roll a new alpha-3 soon, as alpha-2 is old and misses many fixes and features. 

The reason for still being alpha is not open bugs/general stability but rather further possible (breaking) changes.

**Comment by tafli** [comment]
Thanks for the update @marcelmay. Looking forward then for alpha-3.

**Comment by bodiam** [comment]
It seems I'm running in similar issues, and while this issue is closed, I can't find the alpha-3 binary yet. Is this binary created somewhere else, or has it just not been published yet?
