### ISSUE TITLE
Recreating a user isnt possible on greenmail-standalone:1.6.12

### ISSUE THREAD

**Issue by JulianKK** [greenmail-mail-test/greenmail#521]
1. Create user test@test.at
2. Send some mails to user test@test.at
3. Delete user test@test.at
4. create user test@test.at
5. Send some mails to user test@test.at -> throws exception. Not possible to send data to inbox caused by nullpointerexception

**Comment by marcelmay** [comment]
I plan release 1.6.13 for the next few days.

**Comment by marcelmay** [comment]
Thanks alot for the report!

**Comment by JulianKK** [comment]
Thanks for the fix :wink:
