### ISSUE TITLE
GreenMail.isRunning() throws NullPointerException if the server was manually stopped

### ISSUE THREAD

**Issue by bigboynaruto** [greenmail-mail-test/greenmail#536]
`stop()` method sets the `services` property to null ([source](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMail.java#L137)), which causes `isRunning()` method to fail with a `NullPointerExeption` when trying to access `services` ([source](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMail.java#L318))

**Comment by marcelmay** [comment]
Thx alot, @bigboynaruto !
