### ISSUE TITLE
Release 2.1.0-alpha-2

### ISSUE THREAD

**Issue by morki** [greenmail-mail-test/greenmail#565]
Please can you release new version, specifically with this PR https://github.com/greenmail-mail-test/greenmail/pull/554 which we need to use in our application? 

Thank you very much for such a good library! :)

**Comment by marcelmay** [comment]
Will roll a release this weekend

**Comment by marcelmay** [comment]
https://github.com/greenmail-mail-test/greenmail/releases/tag/release-2.1.0-alpha-2
