### ISSUE TITLE
Javadocs are currently a 404

### ISSUE THREAD

**Issue by joelittlejohn** [greenmail-mail-test/greenmail#57]
The Javadocs link at http://www.icegreen.com/greenmail/ and the link in the README.md of this repo point at http://www.icegreen.com/greenmail/javadocs/index.html, which is currently returning a 404.

**Comment by marcelmay** [comment]
Thanks alot! It's fixed now.

**Comment by joelittlejohn** [comment]
Cool. Thanks for the speedy update!

**Comment by camann9** [comment]
Btw: There is also the possibility of downloading the source jar for GreenMail. If you have IntelliJ or eclipse it is pretty simple (google "attach source jar"). Then you get the documentation and you also get the source code and you can debug into GreenMail code.
