### ISSUE TITLE
UID is not passed with POP3

### ISSUE THREAD

**Issue by dswitzer** [greenmail-mail-test/greenmail#58]
We just set up GreenMail to do some testing and we delete messages by their UID. Unfortunately, when pulling messages from POP3, the messages contain an empty UID.

Any chance of getting this changed?

**Comment by buildscientist** [comment]
Hi @dswitzer - any chance you can submit a unit test to verify this? Alternatively I'll see if I can look into this.

**Comment by dswitzer** [comment]
Quickly looking at the code, I would think you could just add something like the following to Pop3ServerTest.testRetrieve():

assertTrue(messages[0].getHeader("uid"));

For me, any attempt to get the UID from a POP message comes up blank. Works fine if I use IMAP.

**Comment by camann9** [comment]
Would you mind quickly cloning the repo and verifying your hypothesis? We don't use any arcane tools so I promise building it and executing the unit tests won't take more than five minutes :-P

**Comment by camann9** [comment]
Actually I am having trouble replicating this. For me in IMAP the uid header is also not set...

**Comment by marcelmay** [comment]
Works now.

1. POP3 UIDL capability was not enabled (#65)
2. Retriever now always fetches UIDs via FetchProfile by default.
3. Example (see Pop3ServerTest.testRetrieve()):
```java
    POP3Folder f = (POP3Folder) messages.getFolder();
    f.getUID(messages[0]));
```

I'm updating the Maven SNAPSHOT for you, so that you give can give it a try till we create the next official release.

**Comment by dswitzer** [comment]
Thanks!
