### ISSUE TITLE
Ability to ignore invalid credentials

### ISSUE THREAD

**Issue by dswitzer** [greenmail-mail-test/greenmail#59]
We're using GreenMail as a test server for our QA/Staging. For our purposes, what would be ideal is GreenMail would just accept any credentials as valid. It would just completely ignore the password and if the username did not exist, would just return an empty mailbox.

We need to be able to test arbitrary mailboxes as part of a workflow system, so for us just always accepting credentials as being valid would be ideal.

**Comment by camann9** [comment]
If you would like to provide a pull request with unit test we would be grateful. There is a user manager that checks credentials so that would be the right point to insert this functionality. Of course it has to be configurable. 
As a workaround you can just send a message to the given mail account then the account is automatically created. 
Is it a big hassle for you to just create the mailboxes before the test is run? I'm afraid I don't really understand your scenario.

**Comment by buildscientist** [comment]
@dswitzer can you provide some additional feedback regarding your requirements? 

For example as @camann9 mentioned GreenMail by default creates a user for any email address that it sends email to. 

Would it be correct in saying that you would like some sort of configuration/property driven option to disable that functionality - e.g. don't automatically create users? 

I can look at modifying the UserManager but need a better understanding of your requirements.

**Comment by dswitzer** [comment]
So it's really two requests:

* accept any password as valid. We use Greenmail to mimic a real mailer
server in our a application for QA. We sometimes need to test against a
production configuration. I'd love if greenmail basically ignored the
password and just accepted anything as valid.

* accept any username as valid. If you send email to a mailbox, a user is
automatically created. I'd like to just connect to any username and if it
doesn't exist, it just returns an empty mailbox. This would allows us to
avoid having to seed Greenmail when we run production tests. Right now, if
I don't seed Grenmail, I get errors back for every mailbox. I'd rather it
treat the mailbox as empty.

Does that help?

On Thursday, October 15, 2015, Youssuf ElKalay <notifications@github.com>
wrote:

> @dswitzer <https://github.com/dswitzer> can you provide some additional
> feedback regarding your requirements?
>
> For example as @camann9 <https://github.com/camann9> mentioned GreenMail
> by default creates a user for any email address that it sends email to.
>
> Would it be correct in saying that you would like some sort of
> configuration/property driven option to disable that functionality - e.g.
> don't automatically create users?
>
> I can look at modifying the UserManager but need a better understanding of
> your requirements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenmail-mail-test/greenmail/issues/59#issuecomment-148576754>
> .
>


-- 
Dan G. Switzer, II
dswitzer@pengoworks.com
http://blog.pengoworks.com/

**Comment by buildscientist** [comment]
The first requirement makes sense. The second not as much. 

Here's where I'm confused: 

You said: 
```
"accept any username as valid. If you send email to a mailbox, a user is automatically created." 
```
This feature already exists. 

Your statement was followed by: 

```
I'd like to just connect to any username and if it doesn't exist, it just returns an empty mailbox.
```
This is what I'm confused about. You want users automatically created - BUT if they do not exist return an empty mailbox? How can I return an empty mailbox when: 

1. The user is automatically created therefore the mailbox is automatically created thereby containing the email you sent to that user.

**Comment by buildscientist** [comment]
Just gave this some additional thought and it sounds like this is what you're looking for: 

1. Allow SMTP/IMAP/POP3 connections using accounts with any password. 
2. If an user account doesn't exist when connecting via SMTP/POP3/IMAP - create an account and return an empty mailbox. 

Is that correct?

**Comment by dswitzer** [comment]
That's correct. I want to be able to connect to a mailbox that doesn't
exist yet. When we do a production test, the mailboxes generally won't
exist in Greenmail. I can seed Greenmail, but for us, it would be more
ideal if Greenmail would just go "ok, this account doesn't exist, let me
automatically create it now and return an empty mailbox."

Thanks!

On Thursday, October 15, 2015, Youssuf ElKalay <notifications@github.com>
wrote:

> Just gave this some additional thought and it sounds like this is what
> you're looking for:
>
>    1. Allow SMTP/IMAP/POP3 connections using accounts with any password.
>    2. If an user account doesn't exist when connecting via SMTP/POP3/IMAP
>    - create an account and return an empty mailbox.
>
> Is that correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenmail-mail-test/greenmail/issues/59#issuecomment-148582940>
> .
>


-- 
Dan G. Switzer, II
dswitzer@pengoworks.com
http://blog.pengoworks.com/

**Comment by buildscientist** [comment]
@dswitzer This feature has been implemented and merged into master. It will be available with release v1.5 which will be rolled in the next week or two.

See - [ExampleDisableAuthenticationTest.java](https://github.com/greenmail-mail-test/greenmail/blob/0e9fda0e7919a3a62d82169428508a8c70065f0b/greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleDisableAuthenticationTest.java) for how to use this.

**Comment by dswitzer** [comment]
Fantastic!

**Comment by jaredculp** [comment]
@buildscientist Is there a way to disable this feature? I'd like to be able to test that invalid credentials are rejected, rather than simply creating a new username/password as is done here: https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/main/java/com/icegreen/greenmail/smtp/SmtpManager.java#L130-L134

**Comment by marcelmay** [comment]
@jaredculp : I'll add this as a new feature #127.

By default, GreenMail did always ignore authentication for SMTP.
