### ISSUE TITLE
SearchCommandParser$SearchOperator cannot be cast to jakarta.mail.search.SearchTerm

### ISSUE THREAD

**Issue by JasterV** [greenmail-mail-test/greenmail#591]
I am sending a SEARCH command with the following query:

```
OR (NOT (SEEN)) (OR (KEYWORD Qd0JTY6EPWA9a5wwvTZ) (KEYWORD InNlCf97T9O6))
```

And it basically breaks the server with the following error

![image](https://github.com/greenmail-mail-test/greenmail/assets/49537445/a5e88ed3-cf4d-41d2-928a-3c6d46b66700)

Is that query not valid in IMAP? Or is it Greenmail that does not support nested OR queries?

**Comment by JasterV** [comment]
# Update

The following query makes it break too:

```
OR (NOT (SEEN)) (SEEN)
```

**Comment by marcelmay** [comment]
Thanks alot, @JasterV ! Will be included in next release (probably rolled this weekend)
