### ISSUE TITLE
is it possible to check via api numbers/content of the mails that have been sent?

### ISSUE THREAD

**Issue by WalkerWalker** [greenmail-mail-test/greenmail#600]
I just deployed the version 2.0.0 via docker

is it possible to check via api numbers/content of the mails that have been sent to the smtp server?
i hope it is already the case, yet I don't find it in the openapi webpage.

**Comment by marcelmay** [comment]
Hi @WalkerWalker!

Currently the api is mostly about configuration/resetting GreenMail, as the standard mail protocols IMAP/POP3/SMTP would be used for verification (e.g. via JakartaMail from a Unit test).

You could easily query via IMAP using tools like [curl](https://gist.github.com/akpoff/53ac391037ae2f2d376214eac4a23634#get-count-of-message-in-mailbox-inbox) .

How would you use a potential API, you're not executing from e.g. a Python script or unit test?

**Comment by WalkerWalker** [comment]
hi @marcelmay 

thank you for the quick reply.  Ideally, I was even thinking about a web interface that can see the mails like the [maildev](https://raw.githubusercontent.com/maildev/maildev/gh-pages/images/screenshot-2021-01-03.png). But now after reading your reply, I now even think it makes perfect sense just to use JakartaMail from a Unit test.

**Comment by marcelmay** [comment]
You could also have a look at https://github.com/davidnewcomb/greenmail-http
