### ISSUE TITLE
`\*` is not a valid IMAP `flag`

### ISSUE THREAD

**Issue by nevans** [greenmail-mail-test/greenmail#633]
The default `FLAGS` response for the `SELECT` command sends `\*`, which is valid for `PERMANENTFLAGS` but not for `FLAGS`.  See RFC3501 or RFC9051:
> The PERMANENTFLAGS list can _also_ include the special flag \\*, which indicates that it is possible to create new keywords by attempting to store those flags in the mailbox.

_(emphasis is mine)_

The relevant formal syntax (note that `*` is not a valid `ATOM-CHAR`):
```abnf
atom            = 1*ATOM-CHAR

ATOM-CHAR       = <any CHAR except atom-specials>

atom-specials   = "(" / ")" / "{" / SP / CTL / list-wildcards /
                  quoted-specials / resp-specials

list-wildcards  = "%" / "*"

flag            = "\Answered" / "\Flagged" / "\Deleted" /
                  "\Seen" / "\Draft" / flag-keyword / flag-extension
                    ; Does not include "\Recent"

flag-extension  = "\" atom
                    ; Future expansion.  Client implementations
                    ; MUST accept flag-extension flags.  Server
                    ; implementations MUST NOT generate
                    ; flag-extension flags except as defined by
                    ; future standard or standards-track
                    ; revisions of this specification.

flag-keyword    = atom

flag-list       = "(" [flag *(SP flag)] ")"

flag-perm       = flag / "\*"

mailbox-data    =/ "FLAGS" SP flag-list

resp-text-code  =/ "PERMANENTFLAGS" SP "("
                  [flag-perm *(SP flag-perm)] ")"
```

And the relevant code is here (I think):
https://github.com/greenmail-mail-test/greenmail/blob/2aa14fc1b3192752f87943c64a60bbf9b4eafac5/greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SelectCommand.java#L50

Perhaps a `mailbox.getFlags()` method could be added that simply filters out `\*` from `mailbox.getPermanentFlags()`?

**Comment by nevans** [comment]
By the way, do you know if any "real" servers respond with `\*` as a (non-permanent) flag?  I ask because I haven't seen any myself and I'd prefer to keep my client protocol parsing code strict

**Comment by nevans** [comment]
oops... I accidentally tapped the close button there!

**Comment by marcelmay** [comment]
Thx alot for the detailed bug report, @nevans .

Regarding you question: I can not say anything about 'real' mail servers, unfortunately.

**Comment by marcelmay** [comment]
Interesting: The SELECT FLAGS result ([availableFlags](https://github.com/eclipse-ee4j/angus-mail/blob/fd8a2e6ee80e7c43d0dc111272c45f2b27e0244c/providers/imap/src/main/java/org/eclipse/angus/mail/imap/IMAPFolder.java#L539)) is more or less ignored in JakartaMail mail implementation ...
