### ISSUE TITLE
greenmail-2.1.0 version release timeline

### ISSUE THREAD

**Issue by SaiYashasvi9** [greenmail-mail-test/greenmail#668]
We are using greenmail for testing smtp functionality. We have removed greenmail-2.0.0 version from our project as it is bringing com.sun.mail.jakarta.mail, it is not complying with org.eclipse.angus.jakarta.mail which we are using in our project. The latest version of greenmail-2.1.0-alpha-3 has that but its not a released version, we cannot add it to our service.
Please let us know the release date of greenmail-2.1.0 version as we are currently blocked with the test automations.
@marcelmay @buildscientist

**Comment by marcelmay** [comment]
@SaiYashasvi9 , 
you should be able to use greenmail-2.1.0-alpha-3.

"alpha" relates rather to still minor unstable/changing API than production-readyness,
and every release (including alpha) must always pass all tests.

2.1 will roll probably around February, once [two known issues](https://github.com/greenmail-mail-test/greenmail/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.1.0-alpha-4) (also impacting old 2.0 version!) are fixed

**Comment by SaiYashasvi9** [comment]
Thanks for your reply
