### ISSUE TITLE
OpenAPI UI is missing 'Get the messages for given user and folder' operation if started as Docker image with '2.0.1' tag

### ISSUE THREAD

**Issue by vlistratenko** [greenmail-mail-test/greenmail#676]
Based on https://greenmail-mail-test.github.io/greenmail/#features OpenAPI provides facilities for some administrative tasks. The doc also mentions that UI may differ depending on how the service is started.

I've started greenmail/standalone:2.0.1 and do not see 'Get the messages for given user and folder' option at all. Please, see all available options: 
![Screenshot from 2024-01-31 00-16-31](https://github.com/greenmail-mail-test/greenmail/assets/16610572/76cc8020-e49d-452e-b285-d70acc6724fb)

Can we have it added? The option looks crucial to me.

**Comment by marcelmay** [comment]
Its a feature recently added to [2.1.0-alpha-4](https://github.com/greenmail-mail-test/greenmail/releases/tag/release-2.1.0-alpha-4) / #673 . Please give 2.1.0-alpha-4 a try ('alpha' in terms of API changes, every release must pass all tests).

**Comment by marcelmay** [comment]
Closing, workaround is to use latest 2.1.x (pre-)release
