### ISSUE TITLE
Do not preload hidden files and files in hidden folders

### ISSUE THREAD

**Issue by An1s9n** [greenmail-mail-test/greenmail#682]
Hi!

First of all thank you for such a great project :)

We use GreenMail in a local k8s cluster (minikube) to check if everything works as expected. It is a common practice for such a scenario to mount emails for preloading into container via configMap volume mount. But k8s adds some extra hidden folders, as a result we obtain exceptions like `com.icegreen.greenmail.store.FolderException: Invalid mailbox name ..2024_02_09_11_29_23.577733621`. My suggestion is to ignore hidden files and files which are in hidden folders during emails preload.

**Comment by marcelmay** [comment]
Thx alot, @An1s9n! Will roll a release soon.
