### ISSUE TITLE
IMAP Content-Type differs POP3 and IMAP

### ISSUE THREAD

**Issue by cshjsc** [greenmail-mail-test/greenmail#706]
When receiving Emails through POP3 the conten-type is not modifed, for example 'text/plain'.
But when receiving with IMAP it gets modified(uppercased) and its 'TEXT/PLAIN', is there 
a special reason why this is done.
This is a problem because while testing signed emails, if the contents of the email get modified the hash doesn't match anymore and my test fail.

I checked the source code and found the problem is caused probably by SimpleMessageAttributes:parseBodyStructure(bool)

**Comment by marcelmay** [comment]
Media type is defined as [case-insensitive](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.3.1).

I will change it to return as provided, and hope it will not cause too many troubles as this might break tests.

**Comment by marcelmay** [comment]
Thx for reporting, @cshjsc !

**Comment by cshjsc** [comment]
Thanks for the quick solution!
