### ISSUE TITLE
IMAPS: Couldnt start at least one of the mail services.

### ISSUE THREAD

**Issue by Paranoid-User** [greenmail-mail-test/greenmail#76]
Hi everyone,

I use GreenMail as a test server for IMAPS unit-testing. In some cases when my PC high-loaded (CPU usage 90%) I faced with the following RuntimeException:

java.lang.RuntimeException: Couldnt start at least one of the mail services.
	at com.icegreen.greenmail.util.GreenMail.start(GreenMail.java:89)
        ...

I guess that this exception caused by slow SSL socked opening (port gets from available) at: com.icegreen.greenmail.server.AbstractServer.openServerSocket(): 57

This operation executed during more than 1 second that is not expected on server start GreenMail.start():75.

Code from start() method:
....
boolean allup = false;
for (int i = 0; i < 200 && !allup; i++) {
     allup = true;
      for (Service service : services.values()) {
            allup = allup && service.isRunning();
      }
      if (!allup) {
           try {
              wait(5);
           } catch (InterruptedException e) {
               // We don't care
           }
      }
}
if (!allup) {
     throw new RuntimeException("Couldnt start at least one of the mail services.");
}
....

Can we do number of iterations or wait timeout configurable by system properties or from server setup configuration?

**Comment by marcelmay** [comment]
I'll have a look at it, either making it configurable or by optionally passing through the timeout in GreenMail.start().

**Comment by Paranoid-User** [comment]
Thank you for reply!
Do you have any ETA about 1.4.2 release?

**Comment by buildscientist** [comment]
@Paranoid-User Hi - this is an open source project and we don't really have any confirmed release schedules. None of us are getting paid to work on GreenMail. Please be patient and the release will come ASAP. If you need the release sooner - please consider submitting a PR and corresponding unit tests.

**Comment by marcelmay** [comment]
Would tmp. a SNAPSHOT version work, too? This will be faster available (eg by the weekend).

We do not have a concrete release plan for 1.4.2 yet.

**Comment by Paranoid-User** [comment]
Sure, it will be great.
Thank you for your time!

**Comment by marcelmay** [comment]
I made the timeout configurable (see [ServerStartStopTest.testServerStartupTimeout()](https://github.com/greenmail-mail-test/greenmail/blob/master/greenmail-core/src/test/java/com/icegreen/greenmail/server/AllocateAvailablePortTest.java) ) :
```java
// Create a few setups
ServerSetup setups[] = ServerSetupTest.ALL;

// Set too low startup timeout
for(ServerSetup s: setups) {
    s.setServerStartupTimeout(3000L); // A very large timeout!
}

// Will fail, as timeouts are set to 0.
GreenMail service = new GreenMail(setups);
```
Note:
- Setting a timeout does not work with GreenMailRule at the moment
- As a hint, you can optimise the GreenMail startup time by only configuring the services you actually required. Especially the SSL based ones such as IMAPS are really slow when starting and therefore also delaying your tests by almost ~100ms.

**Comment by marcelmay** [comment]
FYI, just deployed a snapshot 1.4.2-SNAPSHOT to the [maven snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/com/icegreen/)

**Comment by Paranoid-User** [comment]
Thank you guys. Great job!
