### ISSUE TITLE
Mail is not comming to cc user

### ISSUE THREAD

**Issue by noubar** [greenmail-mail-test/greenmail#765]
I am currently using the docker versions standalone:2.1.0-rc-1 and standalone:2.0.0

My problem is if i send: let assume from user1 to user2 and set user3 as cc

user2 is getting the mail and the mime is correct and shows the line cc: user3
But user3 is not getting the mail in its inbox

**Comment by marcelmay** [comment]
Hi @noubar,

sorry for the delay.

I fail to reproduce the mentioned issue.

The referenced test sends an email to a TO and CC users. Both receive as expected the mail.

I'm closing this issue, feel free to reopen - I would appreciate if you could provide an update of the referenced test for reproduction.
