### ISSUE TITLE
Greenmail SMTP server doesn't handle periods correctly

### ISSUE THREAD

**Issue by randyb** [greenmail-mail-test/greenmail#77]
Per http://tools.ietf.org/html/rfc5321#section-4.5.2 :
>      When a line of mail text is received by the SMTP server, it checks
>      the line.  If the line is composed of a single period, it is
>      treated as the end of mail indicator.  If the first character is a
>      period and there are other characters on the line, the first
>      character is deleted.

`com.icegreen.greenmail.mail.MovingMessage#readDotTerminatedContent` handles the the case of a line containing a single period, but does not handle the case where a line starts with a period and there are other characters.

The end result is mail sent to Greenmail's SMTP server can contain extra periods when retrieved via IMAP or POP3.

**Comment by buildscientist** [comment]
Any chance you can write a unit test for this?

**Comment by randyb** [comment]
I'll give it a shot.

**Comment by marcelmay** [comment]
A simple example could be SmtpServerTest.testSmtpServerBasic, where you set the text body to ".body"?

**Comment by marcelmay** [comment]
Thanks alot, @randyb !
