### ISSUE TITLE
loadEmails not working for directories on Windows primary partition

### ISSUE THREAD

**Issue by gitUserII** [greenmail-mail-test/greenmail#805]
By fixing [Issue #682](https://github.com/greenmail-mail-test/greenmail/issues/682) the `loadEmails` function in `GreenMail.java` got broken on Windows machines, because `C:\` is always hidden. 
![image](https://github.com/user-attachments/assets/76b8b3da-900b-49a8-a7c6-7e8d8992b221)

Even if C:\\ wasn't hidden no directory in `Paths.get(System.getProperty("java.io.tmpdir")` can be used as these directories are created in `C:\Users\user\AppData\Local\Temp` and AppData is also hidden. 

Suggestion: only check for hidden parents that are subdirectories of the used `sourceDirectory`, or use a flag to skip the hidden directory check.

This holds true for OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) on windows 10 and 11.

**Comment by marcelmay** [comment]
@gitUserII , thanks for raising this. Check will only check below sourceDirectory.
