### ISSUE TITLE
Use a code coverage as a service tool

### ISSUE THREAD

**Issue by buildscientist** [greenmail-mail-test/greenmail#81]
There are a number of online code coverage services like [Coveralls.io](http://coveralls.io) and [Codecov.io](http://codecov.io) that allow users to publish code coverage metrics online. 

Given that we want to encourage users to write tests in addition to their PR's - this might be a good way of doing so.

**Comment by marcelmay** [comment]
With Sonar we'd get code coverage and static analysis etc. So http://nemo.sonarqube.org/ would be very helpful

**Comment by buildscientist** [comment]
Closing this as it is identical to #42
