### ISSUE TITLE
UID ranges with a wildcard don't work properly

### ISSUE THREAD

**Issue by rucek** [greenmail-mail-test/greenmail#90]
According to [section 6.4.8](https://tools.ietf.org/html/rfc3501#section-6.4.8) of RFC 3501, when a `*` wildcard is used in an UID range and the mailbox is not empty, at least the last message in the mailbox should be fetched, even if its UID is below the range start:

> Also note that a UID range of 559:* always includes the UID of the last message in the mailbox, even if 559 is higher than any assigned UID value.  This is because the contents of a range are independent of the order of the range endpoints.  Thus, any UID range with * as one of the endpoints indicates at least one message (the message with the highest numbered UID), unless the mailbox is empty.

Greenmail behaves differently, i.e. fetches no messages when the range start is greater than the max UID in the mailbox.

I have already fixed this locally and I'll be submitting a PR shortly.

**Comment by marcelmay** [comment]
Thanks alot for the patch, I'll look into it.

**Comment by marcelmay** [comment]
Pull request looks good - local build runs successful and no Sonar issues.

**Comment by rucek** [comment]
@marcelmay would this fix be released to Maven Central in 1.4.2-SNAPSHOT or is it only scheduled for 1.5? I'm temporarily using my own repo to host the patched version and I'll be happy to switch back to Central as soon as possible.

**Comment by marcelmay** [comment]
@rucek : I updated the SNAPSHOT repo:
https://oss.sonatype.org/content/repositories/snapshots
