### ISSUE TITLE
GreenMail web interface

### ISSUE THREAD

**Issue by cgaulay** [greenmail-mail-test/greenmail#94]
Hi,

there is any web interface to use GreenMail ? for example to list all users on a server ? 
I see there is a greenamil-site directory. how to use it ?

thanks,
Regards

**Comment by buildscientist** [comment]
@cgaulay GreenMail currently does not have a web interface. If you want to list all users on a server call UserManager.listUser() - this will return a collection of GreenMailUsers. 

You can also use the same class to create and delete users. 

As GreenMail is a testing tool - it's most likely we won't be developing a web UI for it. I wouldn't be averse to creating a general purpose REST API to do the things you're asking for though. The project goal though is to keep the overall tool very lightweight - @marcelmay & @camann9 any thoughts on exposing a RESTful API to do the things @cgaulay is requesting.

**Comment by cgaulay** [comment]
@buildscientist Thanks for your answer !
Yes, i know this method listUser(). But we can use it only on a GreenMail server launched like greenmailserver.star(). It can't be used on a GreenMail server launched like a webapp with a WAR file.

It is possible to connect on a smtp server (GreenMail) with GreenMail lib ? 
Thanks in advance.
Regards,

**Comment by buildscientist** [comment]
@cgaulay As I said in my previous comment we don't have an HTTP interface that would allow you to list all configured users in GreenMail. There are a number of things you'll want to keep in mind: 

* If you run Greenmail in a servlet container (e.g. Tomcat or Jetty) - you'll need to configure the users in the web.xml file. See our website's [documentation](http://www.icegreen.com/greenmail/#deploy_webapp) for more details.  
* greenmail-site is actually just static content that is used for our website 
  - @marcelmay we should probably move this into its own GitHub repo under the GreenMail org
* Per our website's [FAQ](http://www.icegreen.com/greenmail/#faq) - GreenMail will accept incoming email to any email account - if it doesn't exist it will be created. 

Hope that helps :)

**Comment by marcelmay** [comment]
Rather than providing a web interface there's a REST API on the roadmap (expose GreenMail API eg via JMX, which is easily exposed as REST via [Jolokia](https://jolokia.org/).

**Comment by buildscientist** [comment]
@marcelmay Jolokia looks like an interesting library but here are my issues with it: 

1. Jolokia exposes JMX/mbean data via HTTP, what does this buy our users? 
GreenMail is a testing tool - who's going to be capturing and monitoring this data?
2. Accessing existing mbeans is done in a very ugly (non RESTful) manner - e.g. to obtain current heap usage I'd make an HTTP GET call on:
```javascript
http://localhost:8080/jolokia/read/java.lang:type=Memory/HeapMemoryUsage
```
The key-value pair in the URI is confusing and not in the least bit RESTful
3. We would have to expose GreenMail settings as mbeans - is that the right approach? It doesn't seem like a clean approach. 

What I'd much do is implement a pure RESTful API using a proven and well known JAX-RS compliant library like [Jersey](https://jersey.java.net). 

Additionally if we need GreenMail related data provided over JMX - we can use something like [Metrics](http://metrics.dropwizard.io/) which will generate data like histograms and timers - data that is useful for performance testers and the like.

**Comment by cgaulay** [comment]
Ok,

thanks a lot.

Charly

**Comment by davidnewcomb** [comment]
I came here looking for the same thing. Had a wander around the interweb and still couldn't see anything that seemed to work out of the box. So I've started writing one.

https://github.com/davidnewcomb/greenmail-http

I'm currently at the _just get it to work_ stage so no judgements on the state of the code!

**Comment by marcelmay** [comment]
@davidnewcomb , 

let me know if you need any core extension, or want your project linked/mentioned from the GreenMail doc.

Yes, there is no 'rich' UI, only a small API exposed by [GreenMail webapp](https://greenmail-mail-test.github.io/greenmail/#deploy_webapp) using an OpenAPI-decsribed-prettified interface for simple interaction.

Function is very limited at the moment, as the API only exposes configured services and users. The idea is to keep the API for managing GreenMail by automation.

**Comment by davidnewcomb** [comment]
@marcelmay Thanks for the tip about the existing API, I'll take a look at that. I came across a few core bugs so I've been fixing them as I go!

A couple of things I need do appear to be hidden at the ends of long chains of objects or with very circuitous routes to get to the information I need, but that may just be my unfamiliarity with the code.

 I'll raise an issue when I need something and we can talk about on a case by case basis.
