### ISSUE TITLE
Squirrelmail read error

### ISSUE THREAD

**Issue by cgaulay** [greenmail-mail-test/greenmail#96]
Hi,

i want to use SquirrelMail for reading mail on my GreenMail server.
The connection is ok, but there is an error on SquirrelMail inbox folder:  
ERROR: Connection dropped by IMAP server.
Query: SEARCH UID 1:*

In GreenMail logs there is theses errors : 

Thread-5911] WARN com.icegreen.greenmail.imap.commands.SearchCommand - Ignoring not yet implemented search command 'UID' java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.UID at java.lang.Enum.valueOf(Enum.java:236) at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:92) at com.icegreen.greenmail.imap.commands.SearchCommand$SearchCommandParser.searchTerm(SearchCommand.java:121) at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:51) at com.icegreen.greenmail.imap.commands.UidCommand.doProcess(UidCommand.java:41) at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:48) at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98) at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51) at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:94) at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:103) at java.lang.Thread.run(Thread.java:744) [Thread-5911] WARN com.icegreen.greenmail.imap.commands.SearchCommand - Ignoring not yet implemented search command '1:*' java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.1:*

Have you any idea for the reason of this issue ? may be a SquirrelMail configuration problem for me

Thanks in advance.
Regards

**Comment by marcelmay** [comment]
Might be related to issue #2.

UID search is currently not implemented, so I'll flag it as an enhancement.

**Comment by marcelmay** [comment]
Fixed in #103.

Note: There was an additional error, see #2 for tracking squirrelmail. Squirrelmail seems to mostly work now, except for some search issues.
