### ISSUE TITLE
Provide a standalone runner for GreenMail

### ISSUE THREAD

**Issue by marcelmay** [greenmail-mail-test/greenmail#98]
Provide a standalone runner for easy testing (eg for the Squirrel issue #96 ).
The standalone runner should be configurable externally via system properties.

**Comment by buildscientist** [comment]
@marcelmay By standalone runner do you mean self contained WAR? Not sure if we want to pull in something like [Spring Boot](http://projects.spring.io/spring-boot/) or [Winstone](http://winstone.sourceforge.net/)

Winstone is lighter weight - but since we already have a GreenMail SpringBean defined.

**Comment by buildscientist** [comment]
@marcelmay Just saw your latest commit - I see what you mean by standalone. Do you think our WAR package would benefit from using something like Winstone?

**Comment by marcelmay** [comment]
Closing this issue for now. 

Possible extensions for standalone runner are
* support reading configuration properties from file: -Dgreenmail.config=my-test-config.properties
